### ISSUE TITLE
watching folders for bulkify / bulk-require

### ISSUE THREAD

**Issue by mattdesl** [substack/watchify#101]
I have a structure like this:

```
  sections/
      home.js
      about.js
  main.js
  routes.js
```

And `routes.js` looks like this:  

```js
var bulk = require('bulk-require')
module.exports = bulk(__dirname+'/sections', ['**/*.js'])
```

If I rename `about.js` to `foo.js` and continue saving files, watchify still uses the old routes (with `about`) until I go in and save the `routes.js` file. Any way around this?

**Comment by zertosh** [comment]
Nope - that's caching at work.
