### ISSUE TITLE
Option to ignore modules in `node_modules`

### ISSUE THREAD

**Issue by andreypopp** [substack/watchify#11]
Basically I have a project template where I use `node-dev` and `browserify`, the browserify is used twice — one instance generates code to execute on server and prerender UI, another — to generate code and serve to client.

When in dev mode it's a **lot** of watchers and it runs out of fds very quickly. I think `watchify` can have an option to ignore modules in `node_modules` cause 99.99% of developers don't need that functionality.

**Comment by nervo** [comment]
:+1: on this, either #31 or #65 implementation

**Comment by zertosh** [comment]
Better late than never :smile: I'm on this!

**Comment by zertosh** [comment]
Closing and moving the discussion to https://github.com/substack/watchify/issues/162.
