### ISSUE TITLE
Potentially an issue with re-building

### ISSUE THREAD

**Issue by JackEllis** [substack/watchify#113]
Hey guys,

A really weird issue I've been having recently:

See here: https://github.com/thejameskyle/marionette-wires/issues/22

Randomly, my watchify etc. (or something) just stops re-building when I save files. I'm unsure what's causing it, but it may be when I open up a new terminal tab.

Problem: The watchify stops working and doesn't re-rebuild
Solution: Restarting my macbook

Also, I started MAMP, which may have interfered? There's nothing obvious port wise though...

Cheers.

**Comment by adaptivdesign** [comment]
I'm having the same issue I believe. Seems like watchify isn't detecting any changes when using version 2.2.1. So i installed watchify@2.1.1 , and everything works again. I'm using a regular gulp recipe.

**Comment by JackEllis** [comment]
I haven't had this happen to me in a while (haven't been doing much JS work) but restarting your machine fixes this. I'd still be curious to know the underlying issue though...
@adaptivdesign

**Comment by adaptivdesign** [comment]
Allright, I think i found mine. I was using a vagrant machine with virtualbox shared folders. Watchify uses chokidar for watching fs changes. Chokidar used to poll my machine for changes in older versions. In later versions this seems to be disabled by default. Sharing folders with vmware, virtualbox or nfs do not trigger fs change events for ionotify. I Decided to use watchify, gulp, etc on my host machine. Now everything works.

**Comment by zertosh** [comment]
Passing `usePolling` to chokidar solves this problem. I'm following that issue in https://github.com/substack/watchify/issues/162.
