### ISSUE TITLE
Changes to files on NFS should be detected

### ISSUE THREAD

**Issue by alexeits** [substack/watchify#120]
Expected: when a watched JS file on a mounted NFS share changes watchify should detect it
Actual: nothing happens, although any local changes are detected correctly

This functionality worked just fine in 2.1.1. It appears to be a regression in 2.2.1.

Setup details:
* OS X Yosemite host
* Ubuntu trusty guest in VirtualBox managed by Vagrant with synced_folder folder mounted via NFS

**Comment by skinofstars** [comment]
Hi, I wanted to add a +1 to this. I seem to be getting the same issue where I am watching files within a vagrant machine that's using NFS. I'm installed from npm using `latest`, so I'm not sure if the aforementioned patch hasn't been released?

**Comment by skinofstars** [comment]
Ok, I tested a bit more and can confirm that patch referenced by greensheep resolves the issue. Is this something that could be merged in? Thanks.

**Comment by blopker** [comment]
The problem with https://github.com/greensheep/watchify/commit/40722d5f66bcac303da45749756eefa330218c7d is that it won't use native file system events on systems that support it, like non NFS mounts. This is a major performance issue. To fix this correctly we need some way of using polling as a fallback if file system events aren't available.

That or allow us to turn on/off polling explicitly through the Watchify API if we know the file system is NFS.

**Comment by skinofstars** [comment]
Ok, well we can check if a file/folder is NFS using the stat command, `stat -f -c %T foo.js`

I'm not sure what system events we're looking for, but I'm happy to do more research. I suspect using stat would be a good enough solution for now though.

**Comment by blopker** [comment]
@skinofstars, it's not just NFS mounts that need polling. There's a discussion over at https://github.com/paulmillr/chokidar/issues/242 (what watchify uses to 'watch') to figure out how to auto-detect what method to use. You should put your .02 in! :+1:

**Comment by zertosh** [comment]
Closing and moving the discussion to https://github.com/substack/watchify/issues/162.

**Comment by zertosh** [comment]
Just published 3.0.0 (see https://github.com/substack/watchify/pull/170), it has the ability to use polling, which will solve your NFS issue.
