### ISSUE TITLE
please consider avoiding "chokidar" as a dependency

### ISSUE THREAD

**Issue by alvint** [substack/watchify#123]
Chokidar (or one of its dependencies) has components written in c++, which means that if it's used as a dependency of Watchify, users will have to have a build chain installed that can handle compiling it. That's not too much of an issue for Linux or OS X, but on Windows getting Node to play well with Visual Studio is notoriously difficult. Effectively, it means that many if not most Windows users can't use Watchify. At least that's what it means at my job because I don't have the time to nurse everyone through the process.

Besides, it just seems wrong that apps written in Javascript should rely on natively built components.

**Comment by bendrucker** [comment]
This is not viable. chokidar's own readme is clear about what its role is and why this can't just be done with plain Node APIs. The [other popular watchers](https://github.com/shama/gaze#why-another-fswatch-wrapper) use C bindings too.

**Comment by alvint** [comment]
@bendrucker - Both "watch" and "watchr" on that list don't seem to require me to compile any C code when I install them. Can one of those be used? Also, I believe Gulp itself uses Gaze. How do they get around requiring users to compile code? Can the same method be used here?

If this is not possible at the moment I would guess that this is a feature that should be baked into Node itself. Does anyone know if there are any pending enhancements for something like this? If not, are there any compelling reasons why this functionality shouldn't be in Node (I'm a Node n00b).

Thanks,
Alvin

**Comment by bendrucker** [comment]
[Gaze has C bindings too](https://github.com/shama/gaze/tree/master/src) where chokidar just relies on fsevents on OS X. I assume you're being asked to compile fsevents. That's not necessary for Windows, but npm does not support platform-specific dependencies (https://github.com/paulmillr/chokidar/issues/164#issuecomment-65420064). 

You're better off attacking this problem at the root and figuring out how to get your dev setup working properly. Not trying to minimize challenges you've had but you're going to miss out on a bunch of major JS tools (including Karma) if a chokidar dep is a nonstarter.

**Comment by alvint** [comment]
@bendrucker - I don't think most people would agree that you should have to install a C/C++ tool chain just to edit Javascript files. And that doesn't answer the first part of the question: why not just use one of the other watchers?

**Comment by alvint** [comment]
When node 11 gets released, you likely won't need Chokidar (or any external watcher) anyway, so no need to get too attached to it.

**Comment by bendrucker** [comment]
I'm not interested in what "most people" think should be the case. In reality these APIs are hard to get right across different platforms. I co-maintain a popular dependent of watchify and getting watching to work and perform well across 3 platforms is hard. chokidar works well and has really moved forward nicely recently when it comes to fixing longstanding issues. I'm not up to date on the `fs` APIs in 0.11, but if they're better that's great.

If first class Windows support is crucial to you, I'd recommend opening a PR if you can find and test a better way to handle this. While "PR > Issue" is almost always true, its especially the case with Windows-related stuff. For most OSS maintainers working around Windows quirks isn't a priority.

**Comment by alvint** [comment]
@bendrucker - We're not talking about a "Windows quirk"; we're talking about Watchify requiring the user to install a C/C++ tool chain. That's the issue here. I don't care if Chokidar is really cool code and I don't care if the maintainers are really nice guys. The end result is that Watchify requires a C/C++ tool chain, and I know from experience that limits its viability.

**Comment by es128** [comment]
@alvint it's been mentioned, but somewhat glossed over in this discussion: Chokidar does NOT require any native bindings. It optionally includes one for the sake of vastly improved performance on OS X, but will run fine on any platform even if that optional dependency is absent.

You do not need a C toolchain to use watchify on Windows, just a bit of tolerance for annoying warning messages from npm that can be safely disregarded. As suggested in the other comment that was linked, if the warning messages bother you enough, please complain about it in npm's issue tracker.

Gaze and Chokidar are the most prominent/popular file watching alternatives, and both involve native C bindings. Any others will have different problems. The node core modules even in 0.11 still have problems as well. But you should feel free to fork and try plugging in an alternate watching solution.

**Comment by alvint** [comment]
@es128 - Whoops, you're right. Something in our Gulp stack is failing on Windows because it's required to be built.  I assumed it was this because it was the first thing I found that used the compiler. Sorry for the false accusation!
