### ISSUE TITLE
Requiring Karma test runner server *before* watchify causes gulp error

### ISSUE THREAD

**Issue by corbanbrook** [substack/watchify#131]
```
var karma = require('karma').server
var watchify = require('watchify')
```

Took me a while to figure this one out but my gulp kept bailing with this error after bundle ran:
```
undefined:0


TypeError: undefined is not a function
``` 

Have only tested with gulp but I would assume there would be issues with other build processes as well.

Simply fixed the issue by requiring the karma server later in the actual 'test' task.

**Comment by zertosh** [comment]
This is super strange. karma and watchify both use chokidar, and that's always a little funky. Thanks for the tip!
