### ISSUE TITLE
ES6 issue with aliasify?

### ISSUE THREAD

**Issue by shipstar** [substack/watchify#134]
(I'm not sure if this is an issue with watchify or aliasify, so feel free to close the issue if needed.)

I have two simple npm scripts at the moment that are identical except for browserify vs. watchify:

    "build": "browserify --extension '.jsx' -t 6to5ify -t aliasify app/index.js -o bundle.js -v -d"`
    "watch": "watchify --extension '.jsx' -t 6to5ify -t aliasify app/index.js -o bundle.js -v -d"

My `app/index.js` file is in ES6 format. When I run `npm run build`, the file compiles successfully. `npm run watch` fails with the following error:

    Error: Line 1: Unexpected reserved word (while aliasify was processing /Users/kshipley/Programming/rms/web-app/js/app/index.js) while parsing file: /Users/kshipley/Programming/rms/web-app/js/app/index.js

[This repo](https://github.com/shipstar/aliasify-or-watchify-bug) is an extremely simple reproduction.

I'm working in a Flux-like architecture, so my overall goal is just to be able to require `app/stores/foo.js` from `app/components/x/y/z/bar.js` without having to back out of arbitrarily deep directory structures (e.g. `import FooStore from ../../../../stores/foo`). If there's a simpler way to do that than aliasify, I'm open to that as a workaround.

**Comment by zertosh** [comment]
After updating the dependencies to:

```
  "devDependencies": {
    "6to5ify": "^4.1.1",
    "aliasify": "^1.7.2",
    "browserify": "^9.0.3",
    "watchify": "^2.6.0"
  },
```
it worked.
