### ISSUE TITLE
The temporary .dotfile is causing a problem with lineman

### ISSUE THREAD

**Issue by jcalfee** [substack/watchify#140]
This stopped working when we upgraded lineman.  I'm deploying to a live directory which then picks it up and re-loads.  Linemen would see that file and throw an error and prevent the deployment from working.

I changed the code to write the dotfile to the current directory then rename it to the output directory which has worked.  You might want to consider an optional temp directory parameter so that you can guarantee the end user can provide a safe place for the file.

https://github.com/substack/watchify/blob/2.2.1/bin/cmd.js#L18

**Comment by zertosh** [comment]
Thanks! I need to investigate what happens on windows when you use `os.tmpdir`.

**Comment by jcalfee** [comment]
Will you reference this ticket on a commit so I will know when or if it gets fixed?   (include #140 in the comment).  It is probably ok to leave the ticket open, that is the easiest way to know.

**Comment by zertosh** [comment]
@jcalfee It's the last thing I need to do for the 3.0.0 release - I plan on wrapping it up later today. Issue: https://github.com/substack/watchify/issues/168 PR: https://github.com/substack/watchify/pull/170

**Comment by zertosh** [comment]
Just published 3.0.0.

**Comment by jcalfee** [comment]
@zertosh that is my only issue.  Thanks for the reference to the other ticket.
