### ISSUE TITLE
Deduped files missing from subsequent bundles

### ISSUE THREAD

**Issue by ben-ng** [substack/watchify#143]
To reproduce: https://github.com/ben-ng/watchify-dedupe-bug

It seems like the first require is fine, but subsequent requires to duplicate files break after the first bundle.

I tried to figure out what was wrong (its a pretty big hinderance to development, not being able to live-reload) but couldn't get anything. Hopefully someone else has better luck!

**Comment by substack** [comment]
It might be the same issue as https://github.com/substack/node-browserify/issues/1101

**Comment by ben-ng** [comment]
Yes, that looks similar. Do you recommend the hotfix? Ive manually deduped my modules for now but thats a fragile temporary measure.

**Comment by substack** [comment]
The hotfix is ok for now. I've added the failing case you put together to the test suite to protect against regressions and in case somebody has a better fix in the future. Published upstream in browserify 9.0.3.

**Comment by ben-ng** [comment]
Excellent! Have a good night.
