### ISSUE TITLE
fullPaths and duplicate react include

### ISSUE THREAD

**Issue by dcousineau** [substack/watchify#145]
I noticed some strange behavior recently and managed to shrink it down to involving pure babel, react, and watchify. **Please excuse if this is a duplicate issue, I'm struggling to come up with good Google-fu so please redirect me if I'm missing something obvious.**

When I have `fullPaths` turned on for that nice pretty watchify acceleration I get `Uncaught RangeError: Maximum call stack size exceeded` errors in my console. This would only happen on a **reload** event as opposed to an initial build. If you look at the following screenshots of some nice pretty diffs:

![](https://s3.amazonaws.com/f.cl.ly/items/2K2g1n2e44071q1C1C1S/Image%202015-02-23%20at%207.12.00%20PM.png)

Above we see my only change: removing a comment.

![](https://s3.amazonaws.com/f.cl.ly/items/1B1x3b1c3Q1j0N02261v/Image%202015-02-23%20at%207.12.07%20PM.png)

If you notice the browserify/watchify adds a second definition for `require('react');` which seemingly sends the browser into an infinite loop trying to require react by requiring react (hence the maximum call stack size exceeded).

Again this doesn't happen when I build by itself in a single pass without watchify and the problem goes away when I turn off `fullPaths` (but I lose the watch optimizations).

I have a [gist here](https://gist.github.com/dcousineau/394c7cd72793a60d9010) containing a minimal*ish* reproduction case, just download the gist, uzip, and follow the README.

**Comment by dcousineau** [comment]
It looks like removing the `.require()` of react from the gulp file also resolves this problem. Curious as to why/how

**Comment by derek-duncan** [comment]
I'm having this same issue. Any ideas?

**Comment by zertosh** [comment]
As of 2.5.0 `fullPaths` is optional. But that change also reworked how the cache is fed. Can you try that version? (Tip: you're running both reactify and babelify. you don't need reactify since babel handles JSX)

**Comment by dcousineau** [comment]
@zertosh I have updated watchify in another project working without fullpaths and it's working flawlessly. I'm going to try the other project that originally spawned this issue when I can today and confirm it works.

**Comment by zertosh** [comment]
Glad it's working for you!

**Comment by ajacksified** [comment]
@zertosh - I'm seeing the same issues, on 3.1.0; it works with `fullPaths: false`, and does not work with `fullPaths: true` (and not having a cache kind of defeats the purpose of using watchify for me). Should I file another issue, or could you re-open this one?

**Comment by zertosh** [comment]
@ajacksified I'd be great if you could open a new issue with a test case I can reproduce :smile:
