### ISSUE TITLE
Error in browser on rebuild

### ISSUE THREAD

**Issue by kumavis** [substack/watchify#148]
`Uncaught TypeError: Cannot read property '0' of undefined`

getting a strange problem on rebuild from watchify
Here is the build code. [sorry about all the gulp](https://github.com/ethereum/vapor/blob/master/gulpfile.js).

I have two entry points and two build modes, for a total of four browserify builds. For all four, I'm using this gulp task generator I threw together [at the bottom](https://github.com/ethereum/vapor/blob/master/gulpfile.js#L146-L185).
only the sandbox.js bundle is giving me a problem, and only on subsequent builds (not the first one)

![image](https://cloud.githubusercontent.com/assets/1474978/6406877/d78bbff8-bdea-11e4-8a29-4f40283a5382.png)

**Comment by kumavis** [comment]
Tracking the issue on my project locally here: https://github.com/substack/watchify/issues/148

**Comment by zertosh** [comment]
Looking at your gulpfile, I think that your watchify instances are all sharing the same cache but shouldn't be. Try:

```js
// from this:
bundler = bundler || watchify(browserify(entryPoint, watchify.args))
// to that:
bundler = bundler || watchify(browserify(entryPoint, {cache: {}, packageCache: {}}))
```

**Comment by zertosh** [comment]
@kumavis Any update on this?

**Comment by kumavis** [comment]
Ended up using https://github.com/kumavis/meowserify to handle my double builds -- thanks for pinging me on this!

**Comment by refractalize** [comment]
I was having this exact problem too, although only since a recent update to browserify/watchify so we thought we were safe for quite a while before it hit us.

Anyway, @zertosh's answer fixed it (so far), I wonder if the documentation or API should be changed so others don't bump into this?
