### ISSUE TITLE
Should wait till whole file is uploaded

### ISSUE THREAD

**Issue by qbolec** [substack/watchify#154]
I use SFTP with Sublime, which uploads files to a server quite slowly.
It seems to me that watchify kicks in too soon, without waiting for the upload to finish, and fails with errors like:
```
{ [Error: ENOENT, rename 'public/.main.js'] errno: -2, code: 'ENOENT', path: 'public/.main.js' }
```
It is highly undeterministic and anoing.

**Comment by zertosh** [comment]
The `.` (dot) files are created temporary while the rebuild is happening. You can fix your issue by using Sublime SFTP's [ignore rules](http://wbond.net/sublime_packages/sftp/settings#setting-ignore_regexes). Just add one for `public/\\.main\\.js`, or whatever pattern fits your builds.
