### ISSUE TITLE
execution fails if verbose is the first argument

### ISSUE THREAD

**Issue by andrefarzat** [substack/watchify#157]
Executing `watchify -v index.js -o out.js` makes the same result as executing `browserify --verbose index.js` which outputs and empty bundle. The same doesn't happen if we change the args order like: `watchify index.js -o out.js -v`

watchify@2.3.0

**Comment by zertosh** [comment]
watchify follows the same [usage pattern](https://github.com/substack/node-browserify#usage) as browserify: `browserify [entry files] {OPTIONS}`. So, `-v` can't go first since that's for entry files.
