### ISSUE TITLE
External source maps and other options.

### ISSUE THREAD

**Issue by Sean-Der** [substack/watchify#16]
First off, thank you so much for watchify, it is a nice little tool!

Currently browserify creates a source map that is base64ed and appended to the bottom of the generated Javascript. By default it uses absolute paths for its sources as well. 

I created an issue against the browserify project, and they responded with the following instructions https://github.com/substack/node-browserify/issues/603#issuecomment-33027983

Would you be interested in a pull request that adds exorcist to watchify, along with some options to configure the output? If you are open to contributions, do you have anythings that you would like to see?

**Comment by AprilArcus** [comment]
thanks for the suggestion to use onchange! nevertheless, adding my +1 to @tonistiigi's feature request.

**Comment by jgoux** [comment]
I'd love to have this feature too. (I'm using the on-change trick atm)

**Comment by zertosh** [comment]
I think this can be implemented relatively easy with [outpipe](https://github.com/substack/outpipe). I'll look into it.

**Comment by zertosh** [comment]
I just published 3.1.0 that adds this - unfortunately, it doesn't work on windows, but file output still works  like always. (See https://github.com/substack/watchify/pull/175). Basically, `-o` can take a shell command, that will be piped the browserify output. E.g.:

``` sh
watchify main.js -o 'exorcist static/bundle.js.map > static/bundle.js' -d
```

``` sh
watchify main.js -o 'uglifyjs -cm > static/bundle.min.js'
```

**Comment by jsilvestre** [comment]
Thank you very much @zertosh , this works like a charm. My build runs under 500ms now, this is so cool!

**Comment by cachaito** [comment]
@zertosh will You consider support Windows users? I find @tonistiigi solution a little bit unfortunate. Why we didn't stick to Browserify syntax solution such:
`browserify main.js --debug | exorcist bundle.js.map > bundle.js` or
`node-sass public/sass/main.scss | cleancss -o public/build/main.min.css`?

Does `watchify main.js -d | exorcist bundle.js.map > bundle.js` is a bad syntax for CLI?

Please remember that escaped pipe like a `^|` is working in Windows :wink:

**Comment by mattdesl** [comment]
Watchify doesn't print to stdout; and it isn't a one-time thing. Unfortunately `watchify main.js -d | exorcist bundle.js.map > bundle.js` would not work.

Just curious: what are the main reasons for wanting external source maps? Is it mainly just so your dev environment can use uglifyjs?

**Comment by mattdesl** [comment]
I was just thinking; maybe this would be possible through a browserify plugin?

```watchify main.js -o bundle.js -p [ exorcism bundle.js.map ]```

/cc @thlorenz

**Comment by cachaito** [comment]
@mattdesl I thought that Chrome DevTools supports only external source maps but I have checked this and apparently stitched source map works too. Anyway, I don't like the idea that watchify doesn't work for all users. I must admit that Your proposal `watchify main.js -o bundle.js -p [ exorcism bundle.js.map ]` which works for example like `watchify scripts/app.js -d -v -o .tmp/js/bundle.js -p errorify` is nice as well.

**Comment by zertosh** [comment]
@cachaito It's not that I have anything against windows users, it's just that for me it's really hard to develop for a platform I don't use. It's really painful to run a windows VM on my slow mac. Plus, I admit, I know next to nothing about windows. Last bug I fixed turned into a mission trying to get git and node running, plus the "Command Prompt" doesn't make sense - it's not like a linux shell.

I'd be more than happy to merge in a PR that got it working. Do you want to submit one?

**Comment by cachaito** [comment]
Sorry @zertosh I don't understand:
>I'd be more than happy to merge in a PR that got it working. Do you want to submit one?

**Comment by zertosh** [comment]
@cachaito If you want to submit a PR for windows support, that'd be great. I couldn't get it to work, but my windows knowledge is very limited.

**Comment by bigtimebuddy** [comment]
After digging for a solution, I just created a Browserify plugin called "mapstraction" which works to extract the sourcemap like exorcist but without the piping https://www.npmjs.com/package/mapstraction

**Comment by AlecRust** [comment]
@bigtimebuddy can mapstraction be used with watchify like this?

```js
watchify main.js -o bundle.js -p mapstraction --debug
```

**Comment by bigtimebuddy** [comment]
@AlecRust should work like that too.
