### ISSUE TITLE
EXDEV error in 3.0.0

### ISSUE THREAD

**Issue by AriaMinaei** [substack/watchify#171]
I got this error after updating to `3.0.0`:
![image](https://cloud.githubusercontent.com/assets/593118/6894848/e84b30ae-d6ee-11e4-92f1-541ff36eb813.png)

This might be because we're storing the dotfile in the temp directory. Looks like watchify is trying to rename a file from the temp directory (in partition C) to the dev directory, which in my machine, is in partition E. Since the two dirs are not in the same partition, rename errors with an `EXDEV`.

[This](http://stackoverflow.com/a/21072354/607997) SO answer is helpful.

**Comment by zertosh** [comment]
Wow I didn't think of that. Thanks for the report and the link. I'll have a fix later today.

**Comment by zertosh** [comment]
Thanks again @AriaMinaei. I published the fix as 3.0.1.

**Comment by AriaMinaei** [comment]
Works beautifully. Many thanks :)
