### ISSUE TITLE
Build still takes 8 seconds with watchify

### ISSUE THREAD

**Issue by TheLudd** [substack/watchify#176]
I have a project where the browserify build is starting to take too long to be built on each file change. I was hoping to improve this with watchify and while the build time is halved, it is still not fast. The first build takes around 15 seconds and subsequent builds takes around 8 seconds.

The thing is that I am using transforms, plugins and source maps and I wonder if the build time is to be expected or if I have configured watchify in the wrong way.

The transforms I am using are `reactify` and `uglifyify`. On top of this I use source maps. What I want is to have the production environment in dev, just add source maps in order to do debugging easier. 
I also have a custom made plugin which takes a list of files and calls `b.require` for all of them. 

This is how I create my watchify instance:
```
var b = browserify({
  debug: conf.sourceMaps,
  cache: {},
  packageCache: {}
})
 .transform('reactify')
 .transform('uglifyify', { global: true })
 .plugin(customPlugin, { files: myFileList })
var w = watchify(b);
```

Is there anything I can do to speed up builds after the first one or am I simply hoping for too much? =)

**Comment by zertosh** [comment]
Subsequent builds should not be taking that long if you're only changing one file. What does the `customPlugin` plugin do?

**Comment by zertosh** [comment]
For some context: We have several builds of React apps at SoundCloud. I've done a lot of manual optimizations so that their initial bundling is ~4-6 seconds with ~400-600ms rebuilds. Below is a section of the gulpfile for the most common build. Take this with a grain of salt - it's very very specific to our needs, so some of it might not work for you:

```js
var b = _.once(function() {
  var b_ = require('browserify')({
    entries: './app/main.js',
    detectGlobals: false,
    noparse: ['immutable', 'rsvp', 'underscore', 'classnames'],
    extensions: ['.jsx'],
    debug: process.env.NODE_ENV !== 'production',
    standalone: 'main',
    cache: {}, packageCache: {} // watchify options
  });
  b_.transform(require('./resources/preprocessor'));
  b_.transform(require('envify'));
  b_.plugin(require('dep-case-verify'));
  if (process.env.NODE_ENV === 'production') {
    b_.transform(require('unreachable-branch-transform'));
    b_.plugin(require('bundle-collapser/plugin'));
    b_.plugin(require('bundle-minify'));
  }
  if (isWatching) {
    b_.plugin(require('errorify'));
    b_.plugin(require('watchify'), {delay: 400, ignoreWatch: true});
    // micro-optimization
    b_.listeners('reset').some(function(handler) {
      if (String(handler).indexOf('(delta / 1000)') !== -1) {
        b_.removeListener('reset', handler);
        return true;
      }
    });
  }
  return b_;
});
gulp.task('main-js', function() {
  return b().bundle()
    .pipe(require('vinyl-source-buffer')('main.js'))
    .pipe(gulp.dest('public/static'))
    .pipe(size({showFiles: true, gzip: process.env.NODE_ENV === 'production'}));
});

gulp.task('watch', function(done) {
  b().on('update', function() { runSequence('main-js'); });
});
```

The only thing that's not public there is the `./resources/preprocessor`. That's just a wrapper for transpilers, so we can have a consistent transpiles between browserify, jest, and node. I'm still trying to  get it right, so I wouldn't base any of your production code on it. Here is one that uses babel:

```js
var babel = require('babel-core');
var path = require('path');

module.exports = require('preprocessor-adapter').create({
  transform: function(src, file) {
    return babel.transform(src, {
      loose: 'all',
      filename: path.relative(process.cwd(), file),
      // sourceMap: 'inline'
    }).code;
  }
});
```

**Comment by TheLudd** [comment]
@zertosh 
Regarding the custom plugin:
> I also have a custom made plugin which takes a list of files and calls b.require for all of them.

**Comment by zertosh** [comment]
@TheLudd: derp, I missed that. Something else I forgot to mention: sourcemaps are expensive. Especially when you're combining them - which is what you're doing with the sourcemaps from `uglifyify` and then from browserify. If you're using `uglifyify` so you can exclude dependencies through dead code removal, then you should try [unreachable-branch-transform](https://github.com/zertosh/unreachable-branch-transform).

**Comment by TheLudd** [comment]
@zertosh My goal is to have the dev environment be as similair as production, including minification/uglification. But in dev, source maps are needed fro debugging and such. 
I noticed that you do the same. 

Of the optimizations you have made, are there any that make as large an impact?

**Comment by zertosh** [comment]
The `noparse` and `detectGlobals: false,` - but that's very project specific. Minification is expensive and you have to make trade-offs. I only apply one round of sourcemaps - not two like yours (maybe even 3 - idk if reactify adds sourcemaps by default).

**Comment by TheLudd** [comment]
I would also like to add one thing to this. I did this little experiment:
```
w.bundle(function(e, res) {
  console.time('secondRun');
  return w.bundle(function(e, res) {
    console.timeEnd('secondRun');
  }); 
});
```
i.e. I create the bundle again without changing anything. I'd assume that the time to compile here would be close to zero but it is still ~8 seconds. Is that an indication of something being wrong? Or does it mean that the transforms cannot be cached or something?

**Comment by zertosh** [comment]
Not necessarily close to zero - it depends. watchify only caches the "deps" step in the [pipeline](https://github.com/substack/node-browserify/blob/9c9370a2463b25b4955ef2807bc1bbca04e97b46/index.js#L369-L383). That's the most expensive step since that's where a module's dependencies are gathered and transforms are applied. Like I said, combining sourcemaps is expensive - that might be your problem. It'd try your test but turning off different sourcemap steps (from uglifyify and/or reactify) to see if that's the problem.

Do you have a repo or something where I can reproduce this?

**Comment by TheLudd** [comment]
@zertosh Turning of the source mapping indeed lowers compile time, so does turning of uglifying. 

I really just want to verify that there was nothing wrong with my configuration described in my original post. If there is nothing wrong with it, then I will have to accept the slow build and try to apply optimizations like the ones you showed.

Unfortunately this is in a private project so I cannot share the code.

**Comment by zertosh** [comment]
Your config looks good. There are perf trade-offs with everything, it's just a matter of finding the right balance.
