### ISSUE TITLE
Option -o with a command: using relative path

### ISSUE THREAD

**Issue by jsilvestre** [substack/watchify#178]
Hi,
Regarding: https://github.com/substack/watchify/pull/175

I made it work very easily thanks to your example, but then I tried to use `./node_modules/.bin/exorcist` rather than the one installed globally, and I got the following error:
```
joseph@macbook:~/cozycloud/tasky$ ./scripts/watch-js 
./node_modules/.bin/exorcist: line 1: syntax error near unexpected token `"SyntaxError: Line 3: Unexpected token : while parsing /Users/joseph/cozycloud/tasky/client/public/scripts/bundle.js.map while parsing file: /Users/joseph/cozycloud/tasky/client/public/scripts/bundle.js.map"'

./node_modules/.bin/exorcist: line 1: `console.error("SyntaxError: Line 3: Unexpected token : while parsing /Users/joseph/cozycloud/tasky/client/public/scripts/bundle.js.map while parsing file: /Users/joseph/cozycloud/tasky/client/public/scripts/bundle.js.map");'

undefined bytes written to ./node_modules/.bin/exorcist client/public/scripts/bundle.js.map > client/public/scripts/bundle.js (NaN seconds)
```

You can find all the relevant information (command that works, command that doesn't, versions) in https://gist.github.com/jsilvestre/8b6ba3bfc9a07477adb2.

I checked to make sure global versions match local versions of the packages:
```

joseph@macbook:~/cozycloud/tasky$ npm view watchify version
3.1.0

joseph@macbook:~/cozycloud/tasky$ npm view browserify version
9.0.4

joseph@macbook:~/cozycloud/tasky$ npm view exorcist version
0.1.6
```

Could it be a bug in https://github.com/substack/outpipe or a misusage from me?

Again, thank you very much for what already exists, it rocks!

**Comment by jsilvestre** [comment]
More (weird) information: if I run 
````
./working.sh
```
It works. If I add a npm command 
```json
"scripts": {
    "dev-working": "./working.sh"
}
```
Then I run:
```
npm run dev-working
```
It doesn't work (same previous mistake).

I am more and more confident that there is something I do not understand, but I can't figure out what.

**Comment by zertosh** [comment]
@jsilvestre I tried it with and without a global excorcist, and they both work. I also tried it without `./node_modules/.bin` in my `PATH`, and it still works. The error you'd see if it were breaking at `outpipe` would be something like `/bin/sh: blah blah blah`.

I don't know why, but I think it might be that your coffeeify transform isn't getting applied. Can you try this:

``` sh
PATH=./node_modules/.bin:$PATH watchify -dv \
    -t coffeeify \
    --extension=".coffee" \
    -e client/src/initialize.coffee \
    -o 'exorcist client/public/scripts/bundle.js.map > client/public/scripts/bundle.js' \
    -x jquery \
    -x underscore \
    -x backbone \
    -x react/addons \
    -x superagent \
    -x node-polyglot \
    -x async \
    -x moment
```

**Comment by jsilvestre** [comment]
Thank you for your answer. Unfortunately, it doesn't fix my issue. I find it very weird that it doesn't work through `npm run watch:js`, but works well with `./scripts/watch-js`.

I think I'm going to push a branch with various files so you can test it in the same conditions I do. Gonna do that tonight after work. Thanks again.

**Comment by zertosh** [comment]
Because it didn't work with `npm run watch:js`, I thought it might be something `PATH` related. Let me know when you have that test up so I can see what's going on.

**Comment by jsilvestre** [comment]
Following your advice, I tried to mess around with my `PATH` and with my global installed packages. I removed watchify and exorcist as global packages, and it's now working. I installed them again, and it's still working.

I don't know what actually happened, but it seems to be all good now. Thank you very much for putting me on the right track!
