### ISSUE TITLE
PHPStorm / System Settings / Use "safe write" stops watchify

### ISSUE THREAD

**Issue by ConneXNL** [substack/watchify#179]
Just came across this issue:
http://stackoverflow.com/questions/27260066/gulp-with-watchify-browserify-runs-twice-then-stops-watching/29412677

After browsing the web for answers for a couple hours I tried editing the file in Notepad instead of PHPStorm IDE. It turned out that browserify/watchify continued to work via notepad.

Thats when I tried to play around with some settings. It turned out PHPStorm / System Settings / Use "safe write", if enabled, stops watchify after PHPStorm edits the file.

All the problems magically disappeared when i turned "safe write" off. I am not sure what IDE you are using, but maybe there is a "Safe Write" option too.

**Comment by zertosh** [comment]
[safe write](https://www.jetbrains.com/phpstorm/help/saving-and-reverting-changes.html):

> modified file will be first saved as a temporary file. If the save operation is completed successfully, the temporary file will renamed, and the original file will be deleted.

Not surprised that that breaks the watcher - since that's not really doing a `change` but an `unlink` then an `add`. I'm not sure that this fixable without some really convoluted logic inside watchify.
