### ISSUE TITLE
Pending state for development tools

### ISSUE THREAD

**Issue by mattdesl** [substack/watchify#180]
One issue during local dev with watchify is refreshing the browser after a file-save but before the re-bundle is complete, causing you to get served with a stale bundle. #86 has proposed this in the past; another solution is to just delete the file before writing to it. Any other ideas?

This could allow tools like beefy/budo/amok/etc to have a better UX.

**Comment by zertosh** [comment]
When used via the command-line, the previous bundle is effectively deleted as soon as browserify starts emitting data. So there is a brief moment between the update event and that, where you could get a stale bundle. I'm not sure that flat out deleting when the update event is emitted is a good idea. But I'm open to be reasoned with :smile: 

But, for when used programmatically, I think https://github.com/substack/watchify/pull/86 is great. You can use that to implement your own logic. If you want to add a quick test to it, I'd be more than happy to merge it.

**Comment by mattdesl** [comment]
What are your thoughts on using events instead of a `isPending()` method?

One idea for the CLI might be `--verbose-json` which spits out ndjson logs for amok/budo/garnish/LiveReactLoad/etc to parse and prettify. 

Sorta off-topic; I opted against the watchify API in budo since it presents some version woes (as a peer dependency), but I might end up switching over since it provides more control.

**Comment by mattdesl** [comment]
Also, unless I'm mistaken, it seems like I might be able to get around this by just checking if the file I received is empty (i.e. mid-bundle)... :+1:

**Comment by zertosh** [comment]
> What are your thoughts on using events instead of a isPending() method?

In this case, I'm not a fan of an event because in order to track whether you're in a particular state, you'd have to fire (and thus listen to) to two separate events. If you're using the API, you can track the pending state by turning it off for watchify and re-implementing it yourself:

```js
var pending;
var w = watchify(b, {delay: 0});

w.on('update', function() {
  pending = true;
  bundle();
});

var bundle = debounce(function() {
  /* write to file */
  pending = false;
}, 600);
```

> One idea for the CLI might be `--verbose-json` which spits out ndjson logs

I had no idea that was thing. Couldn't you implement something similar now that the CLI uses outpipe?

**Comment by mattdesl** [comment]
Thanks, doesn't look like I need anything in watchify changed. :+1: 

> I had no idea that was thing.

It's not really a thing... But I've noticed more CLI authors are using newline-delimited JSON since it can be parsed easily. Otherwise you get tooling [like this](https://github.com/milankinen/livereactload/blob/master/examples/01-basic-usage/scripts/dev), heh. :smile:
