### ISSUE TITLE
Recent issues with budo-chrome

### ISSUE THREAD

**Issue by mattdesl** [substack/watchify#181]
This is a small issue and not exactly a watchify problem, but it only started happening as of 3.0.1 (whereas 3.0.0 is working fine). The current fix is a setTimeout before reading the newly changed bundle.js, which seems pretty sketch.

https://github.com/mattdesl/budo-chrome

It might also affect @caspervonb's amok project. 

Gonna poke around further and see where this problem lies.

**Comment by caspervonb** [comment]
I'll poke around a little bit over the weekend as-well.

**Comment by caspervonb** [comment]
Confirmed, getting back an empty bundle.
Which would be due to the file being created, but not written to yet I suppose?

**Comment by caspervonb** [comment]
Looks like it's due to 99753288d6ddc48bd4d9d928b17544847cf0ea6f
Making an assumption here that we pick up the change event in chokidar from when the write stream is created.

**Comment by zertosh** [comment]
In 3.0.1, I stopped using the temp file, and in 3.1.0, writing of the output file is actually done by [outpipe](https://github.com/substack/outpipe). outpipe does some [weird shit](https://github.com/substack/outpipe/blob/974c973abecb99428c77e6b93ddaa3d162b9ac8f/index.js) - I wonder if that's it.

**Comment by mattdesl** [comment]
Double-checked my versions, my budo-chrome issue only started on 3.0.1. I think outpipe has some other issues which I will post in another thread.

**Comment by mattdesl** [comment]
This is no longer an issue fro me using the API and the latest version of watchify.

**Comment by caspervonb** [comment]
How about, just doing plain ol file writes when it is a file without involving outpipe?

**Comment by mattdesl** [comment]
@caspervonb Yup, that's what the latest changes to outpipe will do. :smile:

https://github.com/substack/outpipe/blob/faedcfb71949809a448e5ff340d4803efb5f3a72/index.js#L13

**Comment by caspervonb** [comment]
Did this get pushed out?  seems like it's still an issue with `"watchify": "^3.1.1"`
