### ISSUE TITLE
Add --version, -v, make verbose short option -V?

### ISSUE THREAD

**Issue by caspervonb** [substack/watchify#182]
Seems more inline with unix tools?

**Comment by zertosh** [comment]
From a quick look at the man pages for `rsync`, `ssh`, and `cp` (just to name a few), it seems that they use `-v` and `--verbose` - like watchify does. And `grep` actually uses `-V` for version - which you can get from npm:  `npm ls watchify`.

**Comment by caspervonb** [comment]
`--version, -V` then :grin:
