### ISSUE TITLE
detect `npm link` changes

### ISSUE THREAD

**Issue by gre** [substack/watchify#189]
In my current setup (OSX, node v0.12.2) I can't make `watchify` supporting symbolic changes (after using npm link and/or npm unlink).

Is that the case only for my setup or is watchify not supporting this feature?

Best regards,
gre

**Comment by zertosh** [comment]
[chokidar](https://github.com/paulmillr/chokidar) is the underlying watcher and it supports [symlinks](https://github.com/paulmillr/chokidar#path-filtering) by default. I just gave it a try on OS X with node v0.10.38 and v0.12.2, and they both work on symlinked modules.

**Comment by gre** [comment]
Hi, sorry my mistake, I actually had a more subtile error and watchify wasn't the cause.

Thanks
