### ISSUE TITLE
infinite rebuild bug

### ISSUE THREAD

**Issue by ahdinosaur** [substack/watchify#190]
in [a project i'm working on](https://github.com/holodex/app), `watchify` now continuously rebuilds forever and ever without end. i haven't figured out the source of the error, my only intuition is it's possibly related to using the [app modules pattern](https://medium.com/node-js-javascript/working-without-frameworks-part-1-b948f281f782) as the project uses that pattern and maybe that's confusing `watchify`, but to help us figure it out i made a [simple example project that reproduces the bug](https://github.com/ahdinosaur/watchify-bug).

## how to reproduce

```bash
# install example
git clone https://github.com/ahdinosaur/watchify-bug
cd watchify-bug
npm install

# run watchify
npm run watch
```

actual output:

```
> watchify-bug@1.0.0 watch /home/user/repos/ahdinosaur/watchify-bug
> watchify . -o bundle.js -v

129006 bytes written to bundle.js (0.68 seconds)
129006 bytes written to bundle.js (0.09 seconds)
129006 bytes written to bundle.js (0.03 seconds)
129006 bytes written to bundle.js (0.04 seconds)
129006 bytes written to bundle.js (0.03 seconds)
... forever and ever ...
```

expected output:

```
> watchify-bug@1.0.0 watch /home/user/repos/ahdinosaur/watchify-bug
> watchify . -o bundle.js -v

129006 bytes written to bundle.js (0.68 seconds)
```

**Comment by wilcosprey** [comment]
I was having the same issue. Just added pull request #191 as a potential fix.

**Comment by ahdinosaur** [comment]
confirmed that #191 fixes the bug. thanks @wilcosprey, i actually attempted a fix based on the same idea but yours' is much nicer, cheers!

**Comment by zertosh** [comment]
https://github.com/substack/watchify/pull/199 fixes this, but it first depends on https://github.com/substack/module-deps/pull/80.

**Comment by zertosh** [comment]
@ahdinosaur and @xtianwill If you update watchify+browserify (so that browserify is using module-deps v3.7.7), this should be fixed. Can you confirm?

**Comment by DavidStrada** [comment]
I'm experiencing the same issue/bug I have updated global and local `watchify / browserify`

```javascript
"devDependencies": {
    "babelify": "^6.0.2",
    "browser-sync": "^2.6.4",
    "browserify": "^9.0.8",
    "es6ify": "^1.6.0",
    "watchify": "^3.1.2"
  }


watchify app/app.js -t babelify --outfile bundle.js --debug --verbose
1752090 bytes written to bundle.js (3.12 seconds)
1752090 bytes written to bundle.js (3.12 seconds)
1752090 bytes written to bundle.js (0.78 seconds)
1752090 bytes written to bundle.js (0.57 seconds)


```

**Comment by zertosh** [comment]
@DavidStrada Can you verify that the version of module-deps is 3.7.7?

**Comment by DavidStrada** [comment]
@zertosh Under `node_modules/browserify/node_modules/module-deps` I see : 

```javascript
"name": "module-deps",
  "version": "3.7.7",
```

**Comment by zertosh** [comment]
@DavidStrada do you have a repo I can test?

**Comment by DavidStrada** [comment]
@zertosh Unfortunately it's a private repo / work, let me try to recreate and remove all of sensitive data.

**Comment by zertosh** [comment]
@DavidStrada try @ahdinosaur's [repo](simple example project that reproduces the bug)? with the CLI command `watchify src/index.js --outfile bundle.js --debug --verbose`?

**Comment by DavidStrada** [comment]
@zertosh Took a while to download the packages but still seeing the same behavior 

```javascript
watchify-bug|master ⇒ watchify src/index.js --outfile bundle.js --debug --verbose
460230 bytes written to bundle.js (3.45 seconds)
460230 bytes written to bundle.js (1.86 seconds)
460230 bytes written to bundle.js (0.32 seconds)
460231 bytes written to bundle.js (0.25 seconds)
460231 bytes written to bundle.js (0.24 seconds)
460231 bytes written to bundle.js (0.24 seconds)

```

**Comment by zertosh** [comment]
@DavidStrada Are you sure you're using the local version? That repo had the bug, but I just confirmed that it's fixed with that same command. Maybe your PATH is setup to use global packages first? You could maybe try: `./node_modules/.bin/watchify src/index.js --outfile bundle.js --debug --verbose`

**Comment by DavidStrada** [comment]
@zertosh Locally works, it's weird given that i updated local / global `browserify/watchify`, I can confirm it's working now `watchify app/app.js -t babelify --outfile bundle.js --debug --verbose`  using  `module-deps v3.7.7`

**Comment by DavidStrada** [comment]
@zertosh  Thanks for the help!

**Comment by xtianwill** [comment]
@zertosh works for me too.

**Comment by ahdinosaur** [comment]
@zertosh works for me, thanks!
