### ISSUE TITLE
`fullPaths` with watchify, when browserify uses -r, results in broken output

### ISSUE THREAD

**Issue by ajacksified** [substack/watchify#195]
Example project at: https://github.com/reddit/reddit-mobile/blob/1b14dd7a2b5d79da6ae97c3c6190600c79f22484/buildTasks/js.js

Clone, npm install, and note the difference between `npm run build` vs `npm run watch`. First build that `watch` does succeeds, but subsequent builds that fire when a file changes cause the error `Uncaught RangeError: Maximum call stack size exceeded` on the client. Appears to have something to do with react trying to require itself.

Seems to be the same issue as https://github.com/substack/watchify/issues/145

**Comment by ajacksified** [comment]
cc @zertosh

**Comment by zertosh** [comment]
@ajacksified So here is what I did using iojs 1.6.3 on os x (couldn't get the server running with node 0.10.38 bc of the generator functions):

```sh
git clone git@github.com:reddit/reddit-mobile.git
cd reddit-mobile
git submodule update --init
npm install

# in one shell
npm start

# in another shell
npm run watch
```

Opened a tab to `http://localhost:4444`. Then I started modifying `src/views/components/Listing.jsx` (changed the title and stuff) and `src/views/components/TopNav.jsx` (messing with the beta label). Kept going back to the site and it all worked fine. No console errors or anything. Sure, the watcher craps out if you have a syntax error, but that's expected (I recommend you try [errorify](https://github.com/zertosh/errorify)).

I went back and re-read your comment in # 145, and I think you might have an old version of watchify installed globally. After 2.5.0, fullPaths is optional and the cache continues to work. If you're seeing a slow down w/o fullPaths, then you're definitely using an old version of watchify.

We have a couple of React apps at SoundCloud. We use watchify in a similar setup to this w/o any problems. Let me know if you can narrow down the steps for me to repro.

**Comment by ajacksified** [comment]
*sigh*. You're right, I was at `2.4.0`, I forgot to re-install after bumping my deps. Thanks, and sorry for wasting your time >.<

**Comment by zertosh** [comment]
heh no worries @ajacksified. I actually enjoyed playing with the reddit mobile site :smile:
