### ISSUE TITLE
Ship 4.0.0

### ISSUE THREAD

**Issue by zertosh** [substack/watchify#207]
Before closing out 3.x:

* [x] Merge https://github.com/substack/watchify/pull/199 (blocked by https://github.com/substack/module-deps/pull/80)
* [x] Some version of https://github.com/substack/watchify/pull/197 (blocked by https://github.com/substack/node-browserify/pull/1222)

4.0.0:

* [ ] https://github.com/substack/watchify/pull/212 - Handle ignore logic inside watchify instead of delegating to chokidar. <del>Essentially some form of https://github.com/substack/watchify/pull/202#issuecomment-93072063.</del> This will bring the semantics of ignoring inline with browserify.
* [ ] Drop `watchify.args` (see https://github.com/substack/watchify/pull/204). Sharing caches is a bad idea for most users. Turning off the cache, or using your own cache will be an opt-in.

**Comment by zertosh** [comment]
@jmm I think the 4.x line will be the last one before the row biz is figured out. So 5.0 is hopefully where we reconcile browserify + watchify + module-deps w.r.t. to the row api.

**Comment by mattdesl** [comment]
:+1: 

Just so I'm clear, the following will still work in 4.x correct?

```js
var b = browserify({ cache: {}, packageCache: {} });
var w = watchify(b);
```

**Comment by zertosh** [comment]
@mattdesl It will. But it I can't actually get rid of having to pass a `{ cache: {}, packageCache: {} }` somehow into browserify like I wanted in https://github.com/substack/watchify/pull/204#issuecomment-93529664.

**Comment by jmm** [comment]
@zertosh What's the upshot of that -- will `watchify.args` be sticking around in some form?

**Comment by zertosh** [comment]
@jmm The `cache` object gets passed to module-deps when a pipeline is created (grep `mopts`). By the time watchify is applied to browserify, a pipeline already exists. So I'd have to dig into `b.pipeline` get module-deps, and modify its options object. Not cool.

But we need some form of `watchify.args` that creates new cache objects - like your PR. Though, that  kinda sucks because if someone keeps using `watchify.args`, it won't break - it'll just silently not cache. Unless we do something like:

```
watchify.args = function() {
  return { cache: {}, packageCache: {} };
};
xtend(watchify.args, watchify.args());
```

But if users have to change from `watchify.args` to `watchify.args()` (or something else), maybe we should leave it as it. Instead change the documentation here, gulp, etc. to explicitly pass `{cache:{}, packageCache:{}}`.

**Comment by jmm** [comment]
@zertosh Ok, thanks, I figured that's what the issue was. I posted some ideas in https://github.com/substack/watchify/pull/204#issuecomment-94877114.

**Comment by zertosh** [comment]
Closing this out for now since things still need to be figured out in browserify regarding path matching.
