### ISSUE TITLE
Update not triggered on (imported) CSS change

### ISSUE THREAD

**Issue by plougsgaard** [substack/watchify#215]
Changes to imported CSS doesn't trigger an update when running *watchify*. I'm suspecting this might be the "correct" behaviour but in case it's not, here's my constructed example.

I run my *watchify* like this: 

`watchify --transform browserify-css --entry entry.js --outfile output.js -v`

The entry file `entry.js` **require**s the CSS file `a.css`. This in turn **import**s another CSS file `b.css`. The problem is that changes to `b.css` doesn't trigger an update.

**Comment by mattdesl** [comment]
Transforms need to emit a "file" event on the transform stream for watchify to pick up new dependencies. You can open an issue with the transform. :smile:

Example:
https://github.com/vuejs/vueify/pull/10/files

ps: @zertosh maybe this should be documented a bit better somewhere ?

**Comment by plougsgaard** [comment]
Thanks for the clarification! :-)

**Comment by jmm** [comment]
@mattdesl 
> maybe this should be documented a bit better somewhere ?

:+1: I was [thinking](https://github.com/substack/watchify/pull/203#issuecomment-93064299) here and mentioned in the browserify transform docs. I could probably do it eventually if someone else doesn't get to it first.

**Comment by zertosh** [comment]
I'm terrible at writing docs - I like writing tests that explain behavior :grin:
