### ISSUE TITLE
Watchify not rebuilding

### ISSUE THREAD

**Issue by TylerK** [substack/watchify#216]
@zertosh As per your direction, here is a new issue with my specs:

* OSX: 10.10.3
* Node: 0.12.2
* NPM: 2.7.5
* Gulp: 3.8.11 (both CLI and local) 
* Browserify: 9.0.8
* Watchify: 3.2.0 

And here is my gulp bundle logic: 

```JavaScript
gulp.task('bundle:dev', function () {
  const projectBundler = function (_bundle) {

    const args = {
      entries         : _bundle.src
      , debug         : true
      , cache         : {}
      , packageCache  : {}
      , fullPaths     : true
    }

    const bundler = watchify(browserify(args).transform(babel, { global: true }))

    const rebundle = function () {

      const start = Date.now()
      util.log(util.colors.cyan('Building ->', util.colors.white(_bundle.name)))

      return bundler
        .bundle()
        .on('error', function (error) {
          ErrorHandler(error)
          this.emit('end')
        })
        .pipe(source(_bundle.outputName))
        .pipe(gulp.dest(_bundle.dest))
        .pipe(reload({ stream: true }))
        .pipe(notify(function () {
          util.log(util.colors.cyan('Finished ->', util.colors.white(_bundle.name), 'in ->', util.colors.white((Date.now() - start) + 'ms')))
        }))
    }

    bundler.on('update', rebundle)
    return rebundle()
  }

  config.bundles.forEach(function (bundle) {
    projectBundler(bundle)
  })
})
```

Let me know if you need any additional info! Much appreciated any attention you can give this problem as it's fairly blocking. :)

**Comment by TylerK** [comment]
Follow up: All of Watchify's tests passed 

```
1..98
# tests 98
# pass  98
```

**Comment by zertosh** [comment]
Nothing jumps out at me from your code. Applying a transform like babel (you mean babelify?) globally is really expensive, but that doesn't affect a rebuilds ability to kick-off. Did you try `poll: true`?

**Comment by TylerLH** [comment]
Is your project in your Dropbox (or similar) folder? I was having the same issue until I realized that was the culprit and moved the project into my regular FS.

**Comment by TylerK** [comment]
@TylerLH Negative, the projects are not in a Dropbox or Google Drive folder. 

Oddly enough, my work computer has the same project and specs as listed above and Watchify runs beautifully.

**Comment by TylerK** [comment]
@zertosh Yep, it is actually Babelify. The global is there due to some folders being symlinked in to node_modules for convenient requiring :)

**Comment by zertosh** [comment]
@TylerK so the exact same project works in one machine but not another? O_O I wonder if it's the symlinks

**Comment by jmm** [comment]
@TylerK If you want to avoid the global transform you can try my [pathmodify](https://www.npmjs.com/package/pathmodify) plugin (although I haven't tried it will `fullPaths` -- don't know if that will make any difference). It'll allow you to use module style `require()` paths, with or without the files being symlinked in `node_modules`, and apply programmatic transforms. Basic usage (assuming calls like `require('app/whatever')` and with or without a symlink at `node_modules/app`) would look like:

```js
var pathmod = require('pathmodify');
args.entries = [/* paths outside of node_modules */];
watchify(browserify(args)
  .plugin(pathmod(), {mods: [
    plugin.mod.dir('app', '/path/to/dir-outside-of-node_modules')
  ]})
  .transform(babel)
)
```

**Comment by TylerK** [comment]
@zertosh Same symlinks too ;) 

I'm going to chalk this up as ghost-in-the-machine for now. I'll keep hammering at this and report back any findings.

@jmm This looks pretty cool, I'm going to give it a shot. Thank you

**Comment by jmm** [comment]
@TylerK thanks. If you have any questions or feedback please open an issue on its repo.

**Comment by alexahn** [comment]
I'm having the same issue, and I've been doing some debugging. In my particular case, it seems that chokadir is not properly working with fse, and I believe it is related to this:
https://github.com/strongloop/fsevents/issues/63

**Comment by blint6** [comment]
* node 0.10.38
* npm 1.4.28
* watchify 3.2.1

Same issue here on Ubuntu linux. Please note that since I've **downgraded to watchify 3.1.2**, I have no more rebuild issue.

`update` event is called well, but the bundle action that follows does not work.

**Comment by JonathanBruce** [comment]
I have a similar issue? I don't believe the problems are the same.

using
* babelify: 6.0.2
* browserify: 10.1.1
* watchify: 3.2.1
* reactify: ^1.1.0

Each rebuild unless I restarted my gulp tasks would be the same as the original startup build. I examined the cache for my index.jsx file and deleted it explicitly

     delete bundler._options.cache['/path/to/file'];

only then do the changes get rebuilt and added to my dist directory.

**Comment by tptee** [comment]
Ran into similar issues on OSX 10.10.4 with the following versions:

iojs: 2.0.1
babelify: 6.1.1
browserify: 10.2.0
watchify: 3.2.1

Watchify triggers sporadically or not at all per gulp session. A workaround (opts.poll) is in this issue: https://github.com/strongloop/fsevents/issues/63

**Comment by lpdumas** [comment]
Had the same issue. @tptee workaround did it for me (the poll opts) ;)

```
const bundler = watchify(browserify(args).transform(babel, { global: true }), { poll: true })
```

**Comment by JonathanBruce** [comment]
awesome that worked for me thanks.

**Comment by burdiyan** [comment]
Didn't work for me. Not rebuilding on update.

```
var gulp = require('gulp'),
    browserify = require('browserify'),
    watchify = require('watchify'),
    source = require('vinyl-source-stream');

var opts = {
    cache: {},
    packageCache: {},
    debug: true,
    entries: './test.js'
};

var b = browserify(opts);
b = watchify(b, {poll: true});

b.on('update', bundle);

function bundle() {
    return b.bundle()
        .pipe(source('bundle.js'))
        .pipe(gulp.dest('./'));
}

gulp.task('build', bundle);
```

**Comment by YourDeveloperFriend** [comment]
I'm running into this issue too, and I was able to get it to work by manually removing the cache on `update`:

```javascript
bundle.on('update', function(filename) {
  delete bundle._options.cache[filename];
  bundle.bundle()
  // gulp stuff
  .pipe(source('app.js'))
  .pipe(gulp.dest('public/js'));
});
```

**Comment by royriojas** [comment]
I have this issue and find it happens intermittently. Some times it works and sometimes it doesn't. It happens more often in Linux environments. Weird thing, using `watchify@2.6.0` works as charm everytime and everywhere...

**Comment by royriojas** [comment]
I was able to manage an scenario where the issue always happen. Basically it goes like this in my case.

If you run `watchify@3.2.3` from an spawned process the issue happens intermittently.
If run it directly it will work normally and not fail.

If you run the same using `watchify@2.6.0` and repeat the experiments above, it works normally.

**Comment by royriojas** [comment]
So the issue is inside the `chokidar` module. If you use `chokidar@0.12.6` no issues at all. Using `chokidar@latest`. Issues happen pretty consistently. I guess this should be reported as a bug on their side then

**Comment by zertosh** [comment]
@royriojas Interesting. So the main difference between 2.6.x and 3.0.0 is chokidar. Can you open a new issue to discuss this?

**Comment by royriojas** [comment]
Sure thing! @zertosh

**Comment by royriojas** [comment]
so actually @zertosh the issue is not really in chokidar I manage to find the difference between 2.6.0 and 3.2.3 in this function

```javascript
function collect () {
        b.pipeline.get('deps').push(through.obj(function(row, enc, next) {
            var file = row.expose ? b._expose[row.id] : row.file;
            cache[file] = {
                source: row.source,
                deps: xtend({}, row.deps)
            };
            watchFile(row.file); // this is missing in 3.2.3 Adding it works again in my case. 
            this.push(row);
            next()
        }));
    }
```

**Comment by zertosh** [comment]
@royriojas That `watch` call was unnecessary. I've experimented with a file cache myself - If you open a new issue with the code you're using, we can come up with something that works for you.

**Comment by royriojas** [comment]
Thanks @zertosh, will do it and prepare an small repo where that can be reproduced.

**Comment by royriojas** [comment]
@zertosh I have created #240 with a link to a repo that can be used to replicate the issue.

**Comment by rashkov** [comment]
Using Linux here. Not sure if this is still the same issue, but I'm finding that even with polling turned on it'll still skip some rebuilds. This issue is much worse on my spinning disk machine than my ssd machine, although it still happens for both. Setting Vim's noswapfile option seems to fix this. Maybe there's some kind of race condition going on? Seems to be sensitive to latency.

**Comment by MrMMorris** [comment]
hi all. Not sure if I am having the same issue that is relevant to this ticket. 

`watchify 3.0.0` with `poll: true` over NFS only runs the initial build and then fails to pick up any subsequent file changes.

**Comment by substack** [comment]
I've been getting this issue sporadically on linux for a while too.

**Comment by substack** [comment]
Issue replicated, pull request sent for review.

**Comment by MrMMorris** [comment]
@substack thanks for the PR! It looks like I may be having an issue similar to yours as I have found some files what work. Look forward to this being fixed!

**Comment by parshap** [comment]
I'm still getting the issue where a certain file "goes bad" and subsequent changes to that file fail to get recognized until I restart the process. Changes to other files will continue to work fine. Using watchify@3.3.1 and browserify@11.0.1 on Ubuntu.

**Comment by MrMMorris** [comment]
yea, I am using 3.3.1 as well and it seems that only a couple files don't trigger a build. Restarting/recreating process doesn't help.

**Comment by zertosh** [comment]
I'm locking this thread because it's gotten too noisy. If you're having rebuild problems please open a new issue with details about your setup and some way to reproduce. I'd really like to help but if I can't reproduce it, then I can't debug it.
