### ISSUE TITLE
Watchify appears to stop (never start?) watching after initial successful run.

### ISSUE THREAD

**Issue by NickGrease** [substack/watchify#225]
When I install Watchify, I get a warning that fsevents0.3.6 can't be installed on Windows. Is there any alternative / work-around?

**Comment by bendrucker** [comment]
That's because fsevents is used by chokidar which is what watchify uses to watch for filesystem changes. You'd actually see the same thing on Linux since fsevents is OS X specific. You can ignore this.

npm doesn't have any concept of platform-specific dependencies so the solution is just to use an optional dep and let it fail with a log message on Windows/Linux.

**Comment by NickGrease** [comment]
Thanks for the reply. I should have mentioned a) That Watchify didn't work after initial run. b) Though I believe I followed all instructions, I must admit I'm still quite new to the Node/npm environment.

Running globally installed Watchify using the command 'watchify main.js -o lib/bundle.js -v' produces the expected results and writes the file correctly. However, after making/saving changes to main.js, nothing happens. The process appears to running. No more messages appear.

This is why I assumed the fsevents might have had something to do with it..., though it was clear after reading/searching that, if that was the case, it was the best kept secret on the internet :)

**Comment by jmm** [comment]
@NickGrease There are some browserify issues that could play a role there. Could you try this as an experiment:

```
watchify /abs/path/to/main.js -o lib/bundle.js -v
```

**Comment by NickGrease** [comment]
@jmm Hi. I've tried with (both|either|or) paths using the full path. No Joy. I've tried installing the 32bit version of node, un/install everything again, set node.exe to run as Admin. I've used the script property of package.json to run watchify as well as at the command prompt - always the same result: it browserify's the file and writes it to the right folder, then never does anything again. No error messages (that I can see, not sure if any logs are hidden anywhere), process is still running, just not catching the change in file main.js after saving.

I'm acutely aware that I seem to be the only one with this problem, which tends to mean user error, but there are so few steps to mess up, I'm at a loss. Thanks for the help.

**Comment by NickGrease** [comment]
Well - technically user error I think. I feel bad - I should feel bad. File path contained a "Projects(Node)" folder. Removing the braces... ya that solved the problem. I've been tinkering with programming for many years, and I forgot rule number one) No special characters in the path. Thanks both, sorry for the trouble.
