### ISSUE TITLE
OSX: fs.watch bounce triggers build twice

### ISSUE THREAD

**Issue by edrex** [substack/watchify#23]
At least on my system `OS X 10.9`, saving a file twiggers two change events:

```watchify -v src/app.js -o app/app.bundle.js```

```touch src/app.js```

Result:

```
1562124 bytes written to app/app.bundle.js
1562124 bytes written to app/app.bundle.js
```

#1 attempts to fix this by adding a debounce with a 2 second window, but on my system the window is a bit larger than that (~2500ms).

What about switching to a non-core file watching lib, such as chokidar (also used by chrisdickinson/beefy)? @substack?

**Comment by zertosh** [comment]
Yup we're using chokidar now.
