### ISSUE TITLE
Error: watch UNKNOWN

### ISSUE THREAD

**Issue by kyra-diablo** [substack/watchify#230]
I've got the following error and could not find a reason why it appeared. 
What does it mean exactly?

```
events.js:85
throw er; // Unhandled 'error' event
^
Error: watch UNKNOWN
at exports._errnoException (util.js:746:11)
at FSEvent.FSWatcher._handle.onchange (fs.js:1157:26)
```

The npm-debug.log has the following extra information:
```
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

**Comment by zertosh** [comment]
Don't know. Why do you have logging about the watcher in your npm-debug.log? Do you have a repro case?

**Comment by kyra-diablo** [comment]
'nmp start' executes the 'watchify app.js -o script/bundle.js -v -d .'
This is why the looging appears in the npm-debug-log I think.

I don't really have a repro case.
First time the error appeared when the 'var testDatagrid = require('react-datagrid');' has been added to a js file, and the error desappeared when the line was removed.
But now the error appeared even though the react-datagrid is not used and no other new external component, and nothing seems to make the error disappear this time.

**Comment by zertosh** [comment]
I'm guessing you've tried the usual stuff: reinstalling your packages, restarting your computer, etc... I'm afraid I need more info to help you out

**Comment by zertosh** [comment]
Any updates?

**Comment by kyra-diablo** [comment]
I´ve tried the usual things you mentioned, but none of them helped. Then I´ve got a tip to use an another package instead of watchify and that turned out well, sorry.

**Comment by phareim** [comment]
This is a cold case, but I've got the same error-message as kyra-diablo here when running gulp on a local folder mapped as a network drive. 

i.e.:
running a watchify gulp-script on [c:\dev\git\myproject\] works as expected. But running the same directory through a mapped network drive [z:\myproject\] fails with the message mentioned above.

node version: 0.12.7
npm version: 2.14.2
gulp version: 3.9.0
watchify version: 3.3.1


kthxbye :)

**Comment by zertosh** [comment]
@phareim Can you open a new issue please? And have you tried polling? It seems to solve a lot of problems with NFS

**Comment by nfriend** [comment]
For what it's worth - just ran into the same error message while running a gulp `watch` task.  I have the same setup as @phareim - my local code repository is mapped to a network drive.  Running my gulp task on the actual directory (not the network directory) worked as expected.

**Comment by martinschaible** [comment]
Now, in 2019 the problem still exists. I got the same error and after copying my project locally, gulp watch runs perfectly. I spent n-1 hours to find a solution. Thanks to everybody.

btw, i'm quite disappointed, that nowadays a pice of software does not run from a network drive.

**Comment by goto-bus-stop** [comment]
If someone knows how to fix it, I'm sure watchify or its dependencies would be happy to accept a PR.
