### ISSUE TITLE
Why does watchify notify of updates to `package.json`?

### ISSUE THREAD

**Issue by codeviking** [substack/watchify#231]
Watchify watches `package.json` files and fires an update whenever they're changed.  It also puts the file package contents into a map, `pkgcache`, but doesn't appear to do anything with them.

A few questions:

1. Why is the watcher in place?  Is the idea that you could write code to dynamically run `npm install` on a `package.json` update, then rebundle?  I can see the utility of this, but there should be a README entry somewhere noting this.

2. What's the purpose of `pckgcache`?

**Comment by zertosh** [comment]
1. https://github.com/substack/watchify/issues/226

2. https://github.com/substack/module-deps/blob/0e290c/index.js#L30

**Comment by codeviking** [comment]
Great!  Thanks, this is helpful.
