### ISSUE TITLE
Add "help" option for the script

### ISSUE THREAD

**Issue by megapctr** [substack/watchify#233]
So there is no help option, which confused me for a second...
```
$ node_modules/.bin/watchify --help
You MUST specify an outfile with -o.
```

**Comment by zertosh** [comment]
You can find the options herer https://github.com/substack/watchify#usage, but a `--help` flag would be nice - PR welcome

**Comment by zertosh** [comment]
How browserify does it would be nice https://github.com/substack/node-browserify/blob/f9c256174fe282f7a8ca619d7168161e8e208524/bin/cmd.js#L9-L22
