### ISSUE TITLE
Segmentation fault when `ionic run`

### ISSUE THREAD

**Issue by ptarjan** [substack/watchify#234]
I have watchify running happily doing its thing using the standard gulp integration:

    $ gulp watch

but then when I go to test my ionic app in another console running

    $ ionic run

Then `watchify` immediately exits. Usually printing

    Segmentation fault: 11

What diagnosis data can I send to help narrow down what is segfaulting? When attaching `gdb` to the gulp process it says it is just exiting normally.

**Comment by zertosh** [comment]
A repo that I can clone and reproduce the issue with would be great

**Comment by zertosh** [comment]
Any updates?

**Comment by ptarjan** [comment]
Its still happening tons, but I just did

    for i in `seq 10000`; do gulp watch; done

which restarts when it segfaults so it is less pressing for me.

It's going to be a bit of a pain for me to setup a repo. Are you on a mac? It keeps crashing when ionic starts to run in the iOS simulator or on a device.

**Comment by zertosh** [comment]
I'm on Yosemite. I don't even know what Ionic is. That's why I'm asking for a repro case. If I can't see the error, then there's not much I can do to fix it :(

**Comment by jedrichards** [comment]
I'm getting the same error, but only with >= iojs 3.1.0. Repro case for me is just to run the following command under iojs 3.1.0:

```
node -e "require('watchify')"
```

Here's my bug for reference: https://github.com/substack/watchify/issues/259
