### ISSUE TITLE
Piping to derequire

### ISSUE THREAD

**Issue by Gijsjan** [substack/watchify#235]
I use the CLI of Watchify to watch and rebuild my (es6, React) project.
    
    #!/bin/sh

    node_modules/.bin/watchify src/index.jsx \
        --detect-globals false \
        --extension=.jsx \
        --external classnames \
        --external react \
        --outfile build/index.js \
        --standalone MyStandalone \
        --transform [ babelify --plugins object-assign ] \
        --verbose

Now, with this build, it cannot find/resolve local require's. Within src/index.jsx I require a local submodule `require("./sub-module")`.

When I use browserify with derequire:

    #!/bin/sh

    node_modules/.bin/browserify src/index.jsx \
        --detect-globals false \
        --extension=.jsx \
        --external classnames \
        --external react \
        --standalone MyStandalone \
        --transform [ babelify --plugins object-assign ] \
        --verbose | derequire > build.index.js

The local file will be found/resolved.

Is there a way to pipe Watchify's output to `derequire`?

**Comment by zertosh** [comment]
yeah, `--outfile`/`-o` can be a shell command (see https://github.com/substack/watchify/pull/175)

**Comment by zertosh** [comment]
So something like this should work:

```sh
#!/bin/sh

node_modules/.bin/watchify src/index.jsx \
    --detect-globals false \
    --extension=.jsx \
    --external classnames \
    --external react \
    --outfile 'derequire > build/index.js' \
    --standalone MyStandalone \
    --transform [ babelify --plugins object-assign ] \
    --verbose
```

**Comment by zertosh** [comment]
Any updates?

**Comment by Gijsjan** [comment]
Excuse me! I took your advise and it worked like a charm, thanks!

**Comment by zertosh** [comment]
np!
