### ISSUE TITLE
Any way to not spawn a chokidar process at all?

### ISSUE THREAD

**Issue by jenius** [substack/watchify#242]
So when you pass `ignoreWatch: true`, it defaults to ignoring everything, not watching any files. However, the watcher process is still spawned if I'm not mistaken, it's just not watching anything. In this case, would it be possible to skip spawning chokidar at all, saving a process?

If the answer is yes, I'd be happy to send in a PR for this change, and if I'm totally off base, which is quite possible, would appreciate any enlightenment!

**Comment by zertosh** [comment]
`ignoreWatch: true` ignores the pattern `**/node_modules/**`, since that was the most common use case for ignoring. If you using that everything is getting ignored, then maybe your entire project is within a `node_modules` dir.

**Comment by jenius** [comment]
Ah, gotchya. So is there any way to implement watchify such that it uses the cacheing system, but no watcher, assuming that I will handle the watching part and trigger a browserify build when needed? I know this is a crazy question but I promise there is a use case behind it :grinning:

**Comment by zertosh** [comment]
Watching does more than just trigger a rebuild, it also invalidates the cache when something changes. You can implement your own caching system in just [a few lines](https://github.com/substack/watchify/blob/3342084cfd95588f7001679b355f45f64af2670b/index.js#L38-L48) (that cache object is consumed by [module-deps](https://github.com/substack/module-deps/blob/0e290cd33b3068b033737375d194e4bf41d4d70c/index.js#L361-L362)).

**Comment by jenius** [comment]
Right. This makes sense, I guess implementing a simple cacheing system manually is the best option here. Thanks @zertosh :grinning:

**Comment by lukehorvat** [comment]
FYI I've extracted watchify's caching into a separate plugin, [rememberify](https://github.com/lukehorvat/rememberify).

If you don't need watchify's file system monitoring (because you're already using something like [gulp-watch](https://github.com/floatdrop/gulp-watch)), then this plugin is a good choice.
