### ISSUE TITLE
noparse option

### ISSUE THREAD

**Issue by Dharmoslap** [substack/watchify#247]
Would be great to have possibility to configure Watchify so it wouldn't parse vendor libraries, like React.js or jQuery. Something like Browserify's noParse.

**Comment by LinusU** [comment]
I believe that all options are passed right thru to browserify, so if it works there it will work here too. Have you tried it?

**Comment by Dharmoslap** [comment]
I haven't tried, there is no reference of it in docs.

**Comment by LinusU** [comment]
From the docs:

> Use `watchify` with all the same options as `browserify` except that `-o` (or `--outfile`) is mandatory.

**Comment by Dharmoslap** [comment]
I see, thanks.
