### ISSUE TITLE
Restarts are slow

### ISSUE THREAD

**Issue by greim** [substack/watchify#251]
Restarting my node process with watchify is slow, because I'm generating lots of bundles. Is it possible to have it store ASTs and/or compiled file strings in some kind process-external cache? Maybe something I can implement/override for the caching piece, in order to store in redis or whatever rather than in memory? Or does this exist already and I just missed it? Thanks.

**Comment by zertosh** [comment]
You can implement another caching strategy [same way](https://github.com/substack/watchify/blob/664f2c3ef04848718504f7b0ca003e76439801fd/index.js#L39-L49) watchify implements an in-memory cache

**Comment by royriojas** [comment]
@greim you can give it a try to [persistify](https://www.npmjs.com/package/persistify) which implements a cache that can be persisted to disk, reducing the time for builds. It is a wrapper over watchify/browserify, so the cli commands should be interchangeable.

**Comment by greim** [comment]
@royriojas - Thanks!
