### ISSUE TITLE
Some files not triggering rebuild

### ISSUE THREAD

**Issue by MrMMorris** [substack/watchify#252]
OSX 10.10.4
Watchify 3.3.2
`poll: true`
NFS

From testing all but **one** file triggers a rebuild. Unfortunately, that is my css file which gets changed the most.

I have tried solutions mentioned here https://github.com/substack/watchify/issues/205#issuecomment-98672850 but have had no luck. The only thing I have not tried is renaming all of  `/Users` (I have tried renaming `/Users/mmorris`) as I am concerned it may break something.

**Comment by MrMMorris** [comment]
nevermind, I'm just an idiot :smile:

**Comment by zertosh** [comment]
I'm curious, what was it?

**Comment by MrMMorris** [comment]
I'm embarrassed to admit is, but it was because I was changing the css file instead of the scss file which is the one being watched :sweat_smile:

Sorry about the hubbub

**Comment by zertosh** [comment]
Ah, it's ok, no worries!
