### ISSUE TITLE
'updating' variable is always true

### ISSUE THREAD

**Issue by t2n** [substack/watchify#256]
'end' event never fires in that part of the code:

``` 
bundle.on('end', onend);
```
therefore grunt-browserify doesn't update my bundles. It was working properly several days ago. I'm using OSX but that's not fsevent bug - invalidate method fires on every dependant file change.

Could you point me the way to investigate this further and find the cause of it ?

Thanks

**Comment by zertosh** [comment]
Make sure that grunt-browserify is actually using browserify 11.0.1 – it has https://github.com/substack/node-browserify/commit/90a429d6c22eefa61f73840ca212e7784666660a which fixes what you're describing.

**Comment by t2n** [comment]
that did the trick, thanks a lot!
