### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by nickdesaulniers** [substack/watchify#257]
I tend to leave watchify running over long durations, and putting my laptop to sleep.  I've seen a few segfaults:
```
...
26489 bytes written to dist.js (0.02 seconds)
[1]    33222 segmentation fault  watchify main.js -o dist.js -v -d
➜  joshVR git:(master) ✗
```
OSX 10.10.3 (14D136)

**Comment by zertosh** [comment]
Hey @nickdesaulniers, I think this is an issue with chokidar that might have been fixed by https://github.com/paulmillr/chokidar/pull/332.

**Comment by nickdesaulniers** [comment]
cool, looks like they need to publish a new version number for a reinstall of watchify to pick it up

**Comment by zertosh** [comment]
Seems like this is resolved (ref https://github.com/paulmillr/chokidar/pull/332#issuecomment-134676783)
