### ISSUE TITLE
Make invalidate method public?

### ISSUE THREAD

**Issue by stephenbunch** [substack/watchify#262]
Hey guys, would it be possible to expose the invalidate method somehow? I've got a project where I need to be able to invalidate the entry file to manually trigger a partial rebuild.

**Comment by zertosh** [comment]
By exposing it, it would then become part of the supported "public api", and I don't think that's a method that should be supported. If you need the method to just invalidate a file(s), not to override the logic, then you can just change the file(s) modified timestamp (see [fs.utimes](https://nodejs.org/api/fs.html#fs_fs_utimes_path_atime_mtime_callback)). That's a modification, and it'll trigger a `change -> invalidate -> update` cycle.

**Comment by stephenbunch** [comment]
Ah, perfect. That should do the trick. Thanks!
