### ISSUE TITLE
Only reloads once per file on ubuntu

### ISSUE THREAD

**Issue by pajtai** [substack/watchify#264]
This happens on Ubuntu but not on my Mac.

I'm running this command:

```
watchify -o app/bundle.js -v -d app
```

with node v0.12.7 on Ubuntu 14.04.2 LTS and watchify 3.4.0

Initially I see a 

```
2403040 bytes written to app/bundle.js (3.47 seconds)
```

Then I change a file and I see a:

```
2402989 bytes written to app/bundle.js (0.39 seconds)
```

but on any further changes to the same file nothing. If I change another file, there is one more write to bundle.js, but nothing on further changes to the file.

**Comment by zertosh** [comment]
That seems like a watcher ([chokidar](https://github.com/paulmillr/chokidar/)) problem - since it affects one platform and not another. You can try to see if polling helps in Ubuntu, otherwise, I suggest you see what you find in chokidar.
