### ISSUE TITLE
watchify global install hangs at SOLINK_MODULE(target) Release/fse.node

### ISSUE THREAD

**Issue by kaidez** [substack/watchify#265]
I'm trying to install watchify globally on node v4.0.0 but the install hangs at the `SOLINK_MODULE(target) Release/fse.node` point. I've tested things by making other global installs and they've installed with no issue...only watchify is a problem.  I've tried to fix the issue by:

-uninstalling/reinstalling node v4.0.0.
-installing v 0.12.7 and then trying to globally install watchify.

Thx in advance.

**Comment by zertosh** [comment]
Works for me: ![tchpt](https://cloud.githubusercontent.com/assets/830952/9832243/a200fa30-5929-11e5-8782-a0fda0be3cd1.png)

What OS are you using?

**Comment by kaidez** [comment]
@zertosh: thx for responding. I'm on Mac OS 10.9. It may be a machine or network issue, but I'm able to install other stuff globally.  Very odd.

**Comment by kaidez** [comment]
Problem solved after a few SO searches. I had to request pages over `http

**Comment by kaidez** [comment]
Problem solved after a few SO searches. I was getting a lot of `'ECONNRESET'` calls the few times the install did NOT hang. Apparently, this was because I was requesting packages over `https` instead of `http`.  So I followed the instructions [here](http://stackoverflow.com/questions/18419144/npm-not-working-read-econnreset) and switched things around like so:

`npm config set registry http://registry.npmjs.org/`

Dunno why things hung due a network when installing watchify globally and not another package, but things are fixed.
