### ISSUE TITLE
Doesn't create output directory automatically

### ISSUE THREAD

**Issue by moander** [substack/watchify#269]
```
$ rm -rf static
$ watchify main.js -o static/bundle.js
{ [Error: ENOENT, open 'static/bundle.js'] errno: -2, code: 'ENOENT', path: 'static/bundle.js' }
```

**Comment by mattdesl** [comment]
This is also an issue with browserify, since it dosen't use `mkdirp` to try and recursively create folders for output.

```sh
browserify index.js -o static/bundle.js
-> ENOENT ...
```

**Comment by substack** [comment]
I would not expect a tool I use to implicitly create subdirectories if I give it a path and subdirectories don't exist. I can't think of any tools that work that way aside from `mkdir -p`.

**Comment by moander** [comment]
Most modern tools seems to create it's output dir automatically.. Especially when it comes to compiler-like stuff, and nice-to-have tools like this. I guess that's why I thought this was a bug and not a feature.

**Comment by technicallyfeasible** [comment]
there should at least be an option to have it create the directory automatically

**Comment by daniloprates** [comment]
I double your disappointment

**Comment by inca** [comment]
Why closed? No reasoning, no explanation, no nothing 😥

**Comment by AggressiveSneeze** [comment]
Following 👍  https://twitter.com/jamesadams0/status/902717827395620864
