### ISSUE TITLE
Use browserify's plugin API in readme?

### ISSUE THREAD

**Issue by lukehorvat** [substack/watchify#270]
Correct me if I'm wrong here, but isn't watchify just a browserify plugin? So why not use the plugin API in the readme?

```javascript
var b = browserify(watchify.args).plugin(watchify);
```

I think it's more readable than wrapping the browserify instance, and it also eliminates the need for separate `b` and `w` variables.

Happy to do a PR if you agree.

**Comment by zertosh** [comment]
It's a question of preference – there are many ways to interact with the API. Your way works, and so does:

```js
var b = watchify(browserify(watchify.args));
```

**Comment by zertosh** [comment]
The readme now shows multiple ways of adding the plugin. (see e8f021771aa5fdb33797eb06f95da6507c4e4e06)

**Comment by lukehorvat** [comment]
:+1: Nice.
