### ISSUE TITLE
TypeError: Cannot read property 'cache' of undefined

### ISSUE THREAD

**Issue by Shurlow** [substack/watchify#276]
Watchify is throwing this error when using with gulp and browserify.

Error occurs at line 14
`var cache = b._options.cache;`

I am using watchify identical to the example in the README does.
This is all the code in my gulpfile as of now..

```
var b  = browserify(watchify.args);
var w = watchify(b)
```

I get the same error when passing the cache option directly to browserify as well.

Thoughts?

**Comment by chippawah** [comment]
@Shurlow What did you do to solve this? Currently getting this error as well.

**Comment by Shurlow** [comment]
@chippawah I ended up switching to webpack actually

But this is a snippet of my config that was working for me:

```javascript
  var props = {
    entries: [scriptsDir + '/main.js'],
    extensions: ['.js', '.jsx'],
    debug : true,
    cache: {},
    packageCache: {},
    transform:  [babelify, looseEnvify, reactify]
  };

var bundler = watchify(browserify(props));
```

**Comment by amalgamatedio** [comment]
FWIW I started getting this error after a fresh `npm install`, and doing separate follow-up `npm install browserify` and `npm install watchify` fixed it. I did both before I tried again so it might have been one or the other or both that fixed it.

**Comment by wioux** [comment]
I followed @amalgamatedio's approach and the issue was fixed after `npm install browserify` (didn't need to separately install watchify).

**Comment by gdsouza1992** [comment]
npm install browserify did it for me too 👍

**Comment by bradisbell** [comment]
The fix for me was to ensure I was using this package as a `plugin` and not as a `transform`.
