### ISSUE TITLE
using watchify with babelify for react transpiling

### ISSUE THREAD

**Issue by httpNick** [substack/watchify#281]
Hello,

With browserify I am using the command:

`browserify -t [ babelify --presets [ react ] ] app.js -o bundle.js`

I installed `watchify` globally, and replaced `browserify` with `watchify`, but nothing happens when I run the command. My terminal just hangs. Am I missing something?

**Comment by substack** [comment]
watchify doesn't [write what it's doing to stdout by default](http://www.faqs.org/docs/artu/ch01s06.html#id2878450). It's doing its job. If you want to see what it's doing, you can pass in the `-v` flag.

**Comment by httpNick** [comment]
@substack okay thanks. I'll give it a shot with the flag.
