### ISSUE TITLE
console.error used for reporting writes?

### ISSUE THREAD

**Issue by vegeta897** [substack/watchify#283]
I'm quite new to node, so please excuse my ignorance.

Why is it that `console.error` is used when a write is completed without error? I'd only like to see my console's error color used when something actually goes wrong, not during normal operation. If there is something special about `console.error` that makes it preferred for this message, I'm curious to know what that is.

**Comment by zertosh** [comment]
Because browserify [uses](https://github.com/substack/node-browserify/blob/bbfabaa77fd18e81fe4fd74e104a8a793660f5c5/bin/cmd.js#L630) stdout to output the actual bundled code. Although that use isn't happening here, keeping the output types and their channel consistent makes sense.
