### ISSUE TITLE
Feature Request: After a failure, show a message on success

### ISSUE THREAD

**Issue by ArtskydJ** [substack/watchify#291]
When I use watchify, I'll sometimes get a parse error:
```bash
> watchify js/index.js -d -o public/bundle.js

Error: Parsing file C:\Users\Michael\Github\slideshow\js\index.js: Unexpected token (34:2)
```

I don't always see the error right away, and when I see it, I'm not sure if it was the most recent compile, or if it was fixed since... I would like to have it show a message like `Success!` when the issue is fixed.

Any thoughts on this? Would a PR be accepted?

**Comment by substack** [comment]
You can use the `-v` switch to print a message every time the build completed successfully.

**Comment by ArtskydJ** [comment]
Because I tend to reflexively save often, a message every time is a bit much.

I'll probably start enabling the `-v` switch for my npm watch scripts.

Perhaps this requested feature is opinionated/out of scope. I'll close this issue. If a maintainer feels that it is in scope, feel free to re-open this issue, and I might make a PR.

**Comment by mattdesl** [comment]
You might like these:

- [errorify](https://github.com/zertosh/errorify) - a plugin that shows errors in the DOM (as well as console), much harder to avoid
- [budo](https://github.com/mattdesl/budo) - a more complete/opinionated tool built on top of watchify, which also shows syntax errors in the browser

eg:

![es6](http://i.imgur.com/Pen6bYu.png)
