### ISSUE TITLE
-bash: watchify: command not found

### ISSUE THREAD

**Issue by danielleng** [substack/watchify#307]
`sudo npm install watchify`

completed successfully, then tried to run 
`watchify main.js -d -o bundle.js -v`

getting a command not found error.

watchify@3.7.0

**Comment by Xanderite** [comment]
Needs to be globaly installed?
`sudo npm install -g watchify`

**Comment by danielleng** [comment]
Thanks, that fixed it! Might wanna make a note in the readme to install it globally.
