### ISSUE TITLE
First build takes more than 100 seconds

### ISSUE THREAD

**Issue by donkeysharp** [substack/watchify#309]
I am using npm scripts for my React build process, ES2015 with Babel transpiler and when I run

`$ watchify frontend/javascript/index.js -o public/assets/js/main.js -t [ babelify --presets [es2015 react] ] -v`

I takes a while (about 100 seconds) the first time I run that command and one result is:

`916666 bytes written to public/assets/js/main.js (111.50 seconds)
`

It happens everyday I first run the command given above.

My third party imports in most of my code are:
```
import React from 'react';
import {render} from 'react-dom';
import { Route, IndexRoute } from 'react-router';
import App from './containers/App';
import { combineReducers } from 'redux';
import { routeReducer } from 'react-router-redux';
import { connect } from 'react-redux';
```

I don't know if this is an issue of watchify or is it something usual?

**Comment by mattdesl** [comment]
What version of npm are you using? Try deleting node_modules, installing npm3 and running everything again. Babel is really slow to build with npm2.

**Comment by donkeysharp** [comment]
> What version of npm are you using? Try deleting node_modules, installing npm3 and running everything again. Babel is really slow to build with npm2.

Indeed, I checked my npm version and it was v2 after I upgraded to npm3 first build using `watchify` time took about 17 seconds.

Thanks a lot for your help I will investigate further about npm3. I will close this issue.
