### ISSUE TITLE
Watchify shouldn't write byte/time notifications to stderr

### ISSUE THREAD

**Issue by lordvlad** [substack/watchify#310]
npm-run-parallel kills itself when it receives bytes on stderr. For example try

```javascript
    package.json

    "watch-js": "watchify src/index.js -d -v -o dist/bundle.js",
    "serve": "http-server",
    "dev": "npm-run-parallel serve watch-js"

**Comment by lordvlad** [comment]
As a workaround I use the following for the time being

```javascript
     package.json
     
     "watch-js": "watchify src/index.js -d -v -o dist/bundle.js 2>&1"

**Comment by mattdesl** [comment]
This sounds like a bug with npm-run-parallel. Many CLI tools write to process.stderr for debug/diagnostics/info logs.

**Comment by lordvlad** [comment]
Do they? Feels kinda wrong though. But thanks for the hint, I'll have a look into the npm-run-parallel source, then.
