### ISSUE TITLE
error "ENOENT on dotfile" started happening in 0.8.2

### ISSUE THREAD

**Issue by mreinstein** [substack/watchify#48]
I'm getting ENOENT errors when changing watched files.

```bash
{ [Error: ENOENT, rename 'assets/javascripts/.wrapp.js']
  errno: 34,
  code: 'ENOENT',
  path: 'assets/javascripts/.wrapp.js' }
```

**Comment by ivan-kleshnin** [comment]
+1

**Comment by gasi** [comment]
+1

**Comment by rodryquintero** [comment]
+1

**Comment by zertosh** [comment]
This is the same issue as https://github.com/substack/watchify/issues/83. I'm tracking it there. I've got a fix in https://github.com/substack/watchify/pull/169. I would really appreciate it if someone test drove it and reported their node and OS version in the PR comments.

**Comment by zertosh** [comment]
The fix was published as watchify@2.6.2

**Comment by Gijsjan** [comment]
I'm running 2.6.2 but still encountering this issue.

    $ watchify src/index.coffee --outfile build/development/js/main.js --transform coffeeify --extension=".coffee" --transform jadeify --extension=".jade" -v

**Comment by zertosh** [comment]
@Gijsjan: Hmm I'm getting reports that it's fixed and I can't reproduce it anymore. Can you tell me what OS and editor you're using? Also, it would be very very helpful if you could give me a repo I could clone, or a full gist, to reproduce the problem.

**Comment by shamansir** [comment]
I have `3.6.0`, but yet started getting this issue with a command like:

```
$ watchify ./src/main.js -t browserify-css -o ./dist/player.js`
```

Output: 

```
{ [Error: ENOENT, rename 'dist/.player.js'] errno: -2, code: 'ENOENT', path: 'dist/.player.js' }
```

Nor watchify, nor other packages were updated or changed.

**Comment by shamansir** [comment]
Hmm, it turned out that the reason is just another `watchify` instance being run in some other/background process.

**Comment by shamansir** [comment]
I think if there could be a friendlier message for that case, that would be good.
