### ISSUE TITLE
Suggesting verbose stream output option in API

### ISSUE THREAD

**Issue by rkulla** [substack/watchify#50]
The verbose command only seems to work on the command-line. (i.e., watchify checks argv in bin/cmd.js), but not in the API when doing a require('watchify'). This would be nice to have as an option to pass when using tools such as Gulp and vinyl-source-stream. 

Please forgive me if this already exists somehow and I'm just not seeing it. I've noticed some tutorial examples passing {debug:true} or {verbose:true} to .bundler.bundle() before pipe()'ing, but I have had no luck with either.

Attempted with:
    "gulp": "~3.6.2",
    "watchify": "~0.8.2",
    "vinyl-source-stream": "~0.1.1"

**Comment by jfairley** [comment]
I am interested in the same (using React / reactify), though using the example from @substack, the output I see is like

```
3683666 bytes written (0.50 seconds)
```

It's definitely an indication that something happened, but not quite the `something.jsx changed` that I was hoping for.

**Comment by james-gardner** [comment]
+1 - It'd be great to know *which* file changed.

**Comment by zoubin** [comment]
@james-gardner 
Perhaps `b.on('update', console.log.bind(console))` could be useful.
See https://github.com/substack/watchify/blob/master/index.js#L149

**Comment by mhkeller** [comment]
+1 Adding which file changed to the output would be very helpful.
