### ISSUE TITLE
Changes to files are no longer detected after specific syntax errors

### ISSUE THREAD

**Issue by rnijveld** [substack/watchify#54]
I get this for example in this case

```
watchify index.js -o build/bundle.js
```

With **index.js**:
```js
var util = require('./util');
console.log(util.test());
```

And **util.js**:
```js
var extra = require('./extra');
module.exports.test = extra.test;
```

And **extra.js**:
```js
module.exports.test = function () { return 5; }
```

Now when I change util.js to something like this:
```js
var extra = require('./extra');--
module.exports.test = extra.test;
```
watchify correctly shows a syntax error (the `--`). However if I change util.js back to what it was, no update event is fired and no bundle is built. If I then continue by saving index.js again, an update event is fired and the bundle is rebuilt. Also, from that point on, changes in util.js are again recognized.

Weirdly, watchify correctly seems to handle syntax errors in extra.js and index.js. I'm not quite sure why that would be the case. I tried a simpler example with only a single or with two files, but could not get it to fail in those cases.

**Comment by zertosh** [comment]
This isn't a problem anymore. If this issue persists, please open a new issue.
