### ISSUE TITLE
Errors not reported (using Gulp)

### ISSUE THREAD

**Issue by colinhowe** [substack/watchify#61]
It's possible I'm being thick but if I change a file to introduce an error then watchify not only stops working (as reported in another issue) but also fails to say that it has errored.

Following the recipe here https://github.com/gulpjs/gulp/blob/master/docs/recipes/fast-browserify-builds-with-watchify.md

**Comment by daedelus-j** [comment]
+1

**Comment by bendrucker** [comment]
The recipe's been updated so this can be closed
