### ISSUE TITLE
Watchify Stops Listening to Dependency Changes After Failed Transform

### ISSUE THREAD

**Issue by sverrejoh** [substack/watchify#64]
When using watchify with for example the reactify transform, and the transform fails, watchify will only listen for changes to the main file, and not it's dependencies.

It looks like a regression of issue #3, and git bisect shows it as introduced in bcda5eb30be1183dd677d74585ed729ce2a486e4 

index.js:

``` javascript
    require("./test.jsx");
```

test.jsx:

``` javascript
    module.export = "test";
```

Run with watchify:

``` bash
    $ watchify  -d -v -t reactify index.js -o bundle.js
```

Watchify will now stop watching test.jsx if you add a syntax error in it (add "..." for example).

**Comment by sanfilippopablo** [comment]
Same here

**Comment by TeffenEllis** [comment]
I switched to Webpack. The configuration had a bit of a learning curve but it's resulted in a much simpler preprocessor.

Here's an example for anyone interested in the switch.
https://github.com/TeffenEllis/react-starter-pack

**Comment by fiatjaf** [comment]
I'm being hit by this. I'm using _coffeify_.
To hell with Webpack.

**Comment by steevel** [comment]
I've got this problem too. Anyone have a working fix or should I try digging into this?

**Comment by ByScripts** [comment]
Same problem here. Using watchify 3.3.1 with gulp and reactify.

After an error watchify no longer listen for changes.

**Comment by btakita** [comment]
I'm having the same issue with watchify 3.3.1.

**Comment by davelosert** [comment]
Same Problem with watchify 3.7.0

**Comment by fiatjaf** [comment]
A suggestion for people facing this problem is to use https://www.npmjs.com/package/browserify-incremental along with some another tool to watch file changes and do actions, for example, http://entrproject.org/. then instead of calling watchify you would call something like `ls | entr bash -c 'browserifyinc app.js -o dist/bundle.js'`.

**Comment by bertho-zero** [comment]
Stackoverflow: [Gulp with watchify/browserify runs twice then stops watching](http://stackoverflow.com/a/29412677/4015726)

> Just came across this issue. After browsing the web for answers for a couple hours I tried editing the file in Notepad instead of PHPStorm IDE. It turned out that browserify/watchify continued to work via notepad.
> 
> Thats when I tried to play around with some settings. It turned out PHPStorm / System Settings / Use "safe write", if enabled, stops watchify after PHPStorm edits the file.
> 
> All the problems magically disappeared when i turned "safe write" off. I am not sure what IDE you are using, but maybe there is a "Safe Write" option too.
