### ISSUE TITLE
Watchify cancels overlapping Grunt Watches

### ISSUE THREAD

**Issue by giannico** [substack/watchify#66]
I'm finding that watches on files in the dependency chain of my Browserify/Watchify bundles are only firing once, and are cancelled after Watchify builds the bundle. For instance, I have a watch that runs JSHint against all my JS that changes within the project.

```
watch: {
    appJs: {
        files: ['src/**/*.js'],
        tasks: ['newer:jshint:appJs']
    }
 }
```

Some of the files in (src/**/*.js) are also included in my Browserify bundle. After my Browserify/Watchify task bundles the files once, my Grunt JSHint watch stops firing. Files that are in this same glob, but aren't in the Watchify bundle (i.e. test spec files), continue to have the watch executed, as expected.

When commenting the following code from watchify/index.js, this problem is fixed (though I'm expecting there are negative side effects of this that I don't understand yet:

```
function invalidate (id) {
    delete cache[id];
    if (fwatchers[id]) {
        fwatchers[id].forEach(function (w) {
            // w.close(); <-- commenting this resolved the issue
        });
        delete fwatchers[id];
        delete fwatcherFiles[id];
    }
```

**Comment by zertosh** [comment]
This isn't a problem anymore. Try the latest version.
