### ISSUE TITLE
Bundle required in wrong order

### ISSUE THREAD

**Issue by sebastiandeutsch** [substack/watchify#67]
Hi,

I was playing around with es6ify. When I use it with browserify everything works as expected, but when I use it with watchify then the bundles are required in the wrong order (yielding a dependency error).

I originally suspected the error in es6ify but maybe it's in watchify:

https://github.com/thlorenz/es6ify/issues/34

I extracted my original code into this demo repository:

https://github.com/sebastiandeutsch/es6ify-test

I also added a seperate branch where you can see the difference between browserify and watchify:

https://github.com/sebastiandeutsch/es6ify-test/commit/6ee42763973efb5fd5ee442763226dee3f0573cb

Any ideas where this behavior comes from?

Best

Sebastian

**Comment by zertosh** [comment]
It's been a long time so I'm going to assume you figured this out. If you're still having problems, please open a new issue.
