### ISSUE TITLE
watchify loses expose binding on update

### ISSUE THREAD

**Issue by neocoder** [substack/watchify#72]
Hi, I'm trying to use watchify with karma but watchify doesn't expose require after the update. After the first bundle() call everything is ok, require is exposed to the global scope, but after update - it's gone.

Here's one of watchify modified tests
```javascript
var test = require('tape');
var watchify = require('../');
var browserify = require('browserify');
var vm = require('vm');

var fs = require('fs');
var path = require('path');
var mkdirp = require('mkdirp');

var os = require('os');
var tmpdir = path.join((os.tmpdir || os.tmpDir)(), 'watchify-' + Math.random());

mkdirp.sync(tmpdir);

var file = path.join(tmpdir, 'main2.js');
fs.writeFileSync(file, 'console.log(555); module.exports = function(){ console.log(123); };');


test('require api', function (t) {
    t.plan(5);
    var w = watchify(browserify(file, watchify.args));
        w.require(file, { expose: 'EXPOSE_TEST' });

    w.on('update', function () {
        w.bundle(function (err, src) {
            t.ifError(err);

            src+='require("EXPOSE_TEST")();';

            t.equal(run(src), '777\n888\n');
            w.close();
        });
    });
    w.bundle(function (err, src) {
        t.ifError(err);

        src+='require("EXPOSE_TEST")();';    

        t.equal(run(src), '555\n123\n');

        setTimeout(function () {
            fs.writeFile(file, 'console.log(777); module.exports = function(){ console.log(888); };', function (err) {
                t.ifError(err);
            });
        }, 1000);
    });
});

function run (src) {
    var output = '';
    function log (msg) { output += msg + '\n' }
    vm.runInNewContext(src, { console: { log: log } });
    return output;
}
```

**Comment by jakemhiller** [comment]
This is definitely happening with our builds as well. The first build will expose the bundle, and subsequent builds will not.

Tested with browserify `8.0.3` and watchify `2.2.1`

**Comment by greypants** [comment]
For now, I'm working around it by ignoring `expose` and `require` when building with watchify, and only factoring out shared dependencies when my browserify task is run directly (sans watchify). Just means that some modules are duplicated across bundles during development. Not a big deal. They get sorted out for production builds.

For reference:
https://github.com/greypants/gulp-starter/blob/master/gulp/tasks/browserify.js#L32

**Comment by zertosh** [comment]
@jakemhiller Is this still a problem with browseify 9.0.3 and watchify 2.6.0? More specifically with watchify 2.5.0 - FYI, after that version `fullPaths` is optional (I think that might be causing you other issues :stuck_out_tongue_winking_eye:)

**Comment by Gijsjan** [comment]
I have the same issue. I'm using npm as a build tool with:

    watchify src/index.coffee --outfile build/development/js/main.js --transform coffeeify --extension=".coffee" --transform jadeify --extension=".jade" --require backbone --require jquery --verbose

browserify `9.0.3` and watchify `3.0.0`

**Comment by zertosh** [comment]
@Gijsjan: @neocoder's test passes. I'm not sure that you're seeing is the same problem. Can you open a new issue with a reproducible test? Or a repo I can checkout? Anything that'll let me see the problem.

**Comment by pbouzakis** [comment]
That's a shame I've been seeing this issue for a few months. Upgraded to browserify 9 and the issue remains.

It only occurs on modules specified with via require method with an expose opt.

**Comment by zertosh** [comment]
@pbouzakis Can you help me out with some way to reproduce it? Like a test or repo? something?

**Comment by pbouzakis** [comment]
Yes I love to. Unfortunately I can easily repro it in my private large git repo.

Tomorrow I'll try to recreate in a simple public repo I can share.

Thanks @zertosh !

**Comment by zertosh** [comment]
@pbouzakis If you want to ping me directly instead of publishing a public repo, my email is my user at gmail.

**Comment by pbouzakis** [comment]
@zertosh Really appreciate that. Just sent you an email.

**Comment by cheapsteak** [comment]
Can anyone who's previously run into this bug confirm if it's been fixed or still there?

**Comment by matthewmueller** [comment]
Still an issue
