### ISSUE TITLE
Fullpaths: undesired local system output

### ISSUE THREAD

**Issue by DominicTobias** [substack/watchify#78]
Sorry this might not quite be the appropriate place for this.

Just spent a couple of hours scratching my head trying to figure out why my output bundle was riddled with full system paths on my local machine until I discovered it was this option from `watchify.args`:

    fullPaths: true

In the docs I see:

> When creating the browserify instance b you MUST set these properties in the constructor:
> 
> var b = browserify({ cache: {}, packageCache: {}, fullPaths: true })

Removing `fullPaths: true` fixes my issue though I haven't tested if the code actually runs yet. Why is this option not optional? Is everyone using this plugin happily bundling their personal system paths in builds or is there a way around this?

**Comment by zertosh** [comment]
`fullPaths` is now optional as of v2.5.0
