### ISSUE TITLE
cache undefined inside invalidate()

### ISSUE THREAD

**Issue by jonathanpmast** [substack/watchify#88]
It would appear that cache doesn't always get initialized to an empty object. 

I was working with beefy on a browserify prototype and it would throw a null exception because the cache variable is undefined inside the invalidate method.  This would happen as soon as watchify found a file change and called invalidate().

I was able to work around the issue by instantiating the cache variable if it wasn't found in browserify's options: var cache = b._options.cache || {};

I did a quick cursory look into the browserify source and couldn't see anywhere cache was created... but I'm probably not looking int he right place :( ...

This may be something that I'm doing wrong, too! :)

**Comment by zertosh** [comment]
The `cache` variable is used by [module-deps](https://github.com/substack/module-deps/blob/574ed9a57cc637480a93b3072659cd5a0eca6435/index.js#L348-L349). If you don't pass a `cache` object like @ryanatkn suggests, you won't get the benefit of the cache. But as of v1.0.3, not passing it, won't cause watchify to throw.
